import { w } from './../utils/utils.js';

export default {
  title: `Current Favs. Food, Beauty, Home Decor, Interactive Workbooks, Fallish Candles, Tech`,
  type: 'movie',
  id: '538e5zkk3xim2sr',
  thumbnail: '538e51d0k3xim575',
  header: `Current favs. Food, beauty, home decor, interactive workbooks, fallish candles, tech.`,
  author: { name: "Renee Amberg", url: 'https://www.youtube.com/channel/UCwrck-lD9ERHLWxWDD8_uyA' },
  link: { name: 'Youtube', url: 'https://www.youtube.com/watch?v=UrIFlTdekXc' },
  id: 'UrIFlTdekXc',
  subtitles: new Map([
    ['00:00', `hello everyone welcome back to my`],
    ['00:01', `channel my name is rene for those of you`],
    ['00:03', `guys that are new today's video is going`],
    ['00:05', `to be a favorites video these are some`],
    ['00:06', `products that I've been obsessed with`],
    ['00:08', `for this month this season currently`],
    ['00:11', `like I'm just obsessed with these things`],
    ['00:13', `right now the first thing that I'm`],
    ['00:15', `obsessed with is mix tiles so they`],
    ['00:18', `actually sponsored a separate video from`],
    ['00:19', `this and I just love it so much that I`],
    ['00:21', `was like I have to like promote them`],
    ['00:23', `again so basically they're like these`],
    ['00:24', `little art canvasses that you can like`],
    ['00:26', `peel and stick onto your walls there's`],
    ['00:27', `no nails or anything like that you can`],
    ['00:29', `literally peel them off put them back on`],
    ['00:31', `like so many different times and they`],
    ['00:33', `stay stuck like on your wall I don't`],
    ['00:35', `know how they do it but it's really cool`],
    ['00:37', `and I have like all of them kind of like`],
    ['00:39', `spread throughout my house right now and`],
    ['00:41', `I just put them up and it looks so nice`],
    ['00:43', `and it kind of adds some like`],
    ['00:45', `personalization into my house I never`],
    ['00:47', `was one to kind of put like my pictures`],
    ['00:50', `out or my family and just seeing them on`],
    ['00:52', `my wall every day just like I feel so`],
    ['00:55', `good I like it I really like it I think`],
    ['00:57', `the quality was amazing I got the ones`],
    ['00:59', `that are called ever I think that's the`],
    ['01:01', `style that I got um and they're just`],
    ['01:03', `kind of white with like a little white`],
    ['01:05', `border on the inside and they just look`],
    ['01:06', `super super like aesthetically pleasing`],
    ['01:08', `you can like throw some on your desk`],
    ['01:11', `I threw like one over here I don't know`],
    ['01:14', `if you guys can see it the quality was`],
    ['01:16', `so surprisingly amazing and it looks`],
    ['01:18', `like something that you spent a lot of`],
    ['01:19', `money on but they're so freakin cheap`],
    ['01:21', `I'm gonna just shamelessly plug my promo`],
    ['01:23', `code in cuz if you guys want to get them`],
    ['01:25', `for yourselves like just use the code`],
    ['01:26', `Renee 10 you guys can get 10% off and`],
    ['01:29', `but this video is not sponsored by them`],
    ['01:30', `in any way I just really really really`],
    ['01:32', `really really like them the second thing`],
    ['01:34', `that I've been obsessed with is my iMac`],
    ['01:37', `I literally have been waiting to get an`],
    ['01:41', `iMac for like the longest time I always`],
    ['01:43', `told myself like once I hit a certain`],
    ['01:45', `threshold in my career I'm gonna buy`],
    ['01:47', `myself a MacBook all right an iMac and I`],
    ['01:50', `just like never had the courage to do it`],
    ['01:51', `because they are a little bit pricey but`],
    ['01:53', `I saw that they had like 5k ones out I`],
    ['01:56', `wasn't aware of the size of them`],
    ['01:59', `honestly like when I got this in the`],
    ['02:01', `mail I was like holy crap that's huge`],
    ['02:03', `but it honestly makes me want to work`],
    ['02:05', `and makes me want to be productive I'm`],
    ['02:07', `obsessed with it the quality of my`],
    ['02:09', `content now is just like so so good I`],
    ['02:13', `posture is better and I just think it's`],
    ['02:15', `a really great investment because max`],
    ['02:16', `lasts so long I remember like when I`],
    ['02:19', `used to buy like pcs all the time I`],
    ['02:21', `would literally have them for a year and`],
    ['02:24', `then they would just like go get like a`],
    ['02:27', `virus or something but the thing I liked`],
    ['02:28', `about max is that they don't get viruses`],
    ['02:30', `so I know that like once I bought this`],
    ['02:32', `like I would never have to buy another`],
    ['02:33', `desktop unless I really really really`],
    ['02:35', `wanted to because it's just gonna last`],
    ['02:37', `so freakin long and I just feel so`],
    ['02:39', `official now that I have a Mac desktop`],
    ['02:42', `and I'm like seriously obsessed with it`],
    ['02:45', `obsessed by the way everything that I`],
    ['02:46', `mentioned here will be linked in the`],
    ['02:47', `description box I don't think I said`],
    ['02:49', `that if you guys want to shop them for`],
    ['02:50', `yourselves`],
    ['02:51', `just pop yourselves in the description`],
    ['02:53', `box and they'll be links to everything I`],
    ['02:54', `ended up going to Bath and Body Works`],
    ['02:55', `and picking up some candles it wasn't`],
    ['02:57', `really fall time yet I don't know that`],
    ['02:59', `they have their fall candles out already`],
    ['03:01', `which is very tempting I'm very like`],
    ['03:03', `particularly with seasons or even`],
    ['03:05', `holidays like don't celebrate them until`],
    ['03:08', `they are here because then it just takes`],
    ['03:10', `away from the feelings of the season or`],
    ['03:12', `the holiday you know like I hate when`],
    ['03:14', `people 1 put their Christmas trees out`],
    ['03:16', `before December or to leave their lights`],
    ['03:19', `on for like months after December`],
    ['03:21', `because I'm like you're defeating the`],
    ['03:23', `purpose of Christmas so I didn't buy any`],
    ['03:26', `fall candles I did buy Kingham I think I`],
    ['03:29', `showed this one before and it's one of`],
    ['03:30', `their newer scents and I've never been`],
    ['03:34', `one to buy the same scent from body`],
    ['03:36', `works twice in a row because I like to`],
    ['03:38', `give myself some variety but this one is`],
    ['03:41', `gonna be like a staple now like I feel`],
    ['03:42', `like every time I got about the body`],
    ['03:44', `works I'm gonna buy this candle this is`],
    ['03:46', `the sweetest like cleanest smell I don't`],
    ['03:49', `know how to describe it it's blue fresh`],
    ['03:50', `freesia white peach fresh Clementine`],
    ['03:54', `with essential oils oh my god I wish I`],
    ['03:57', `can just give this to you guys but if`],
    ['03:58', `you guys go into Bath & Body Works smell`],
    ['04:00', `this and I'm like I'm obsessed with this`],
    ['04:03', `set it's always always gonna be my house`],
    ['04:05', `now like I haven't had a candle like`],
    ['04:07', `that with Bath and Body Works I always`],
    ['04:09', `like buy different ones and just like`],
    ['04:11', `them all but this one was so good that`],
    ['04:13', `I'm like wow even like the look of it`],
    ['04:14', `like I really like the like patchy blue`],
    ['04:17', `look it's like aesthetically pleasing as`],
    ['04:19', `well it's just an all-around good candle`],
    ['04:21', `for just like basic necessity there's no`],
    ['04:24', `there's no theme or season`],
    ['04:26', `to it so so good so the other one that I`],
    ['04:30', `picked up is Honey Crisp apple like I`],
    ['04:33', `said fall time is around the corner and`],
    ['04:34', `I feel like the Apple cents are sweet`],
    ['04:37', `enough to be like a summer candle but`],
    ['04:39', `then at the same time it's an apple so`],
    ['04:41', `like you're veering into fall so this is`],
    ['04:44', `a good transitional candle you guys I'm`],
    ['04:46', `obsessed with candles I feel like so`],
    ['04:47', `weird you I'm just talking like this you`],
    ['04:48', `guys were probably like she's freaking`],
    ['04:50', `crazy about candles I am I couldn't`],
    ['04:52', `totally admit that this one is a white`],
    ['04:53', `barn one which I real is being an white`],
    ['04:55', `barn no this is so they have two`],
    ['04:58', `different stores now I think once bath`],
    ['05:01', `and Bodyworks ones white barn and I`],
    ['05:03', `think white barns are more like the look`],
    ['05:06', `it's like more of an aesthetic but I'm`],
    ['05:08', `obsessed with just a look of this candle`],
    ['05:11', `all speaking of it looks like kind of`],
    ['05:12', `just black paint brushed on and I think`],
    ['05:14', `it's just so nice I love the gold`],
    ['05:15', `accents here when I first got this one I`],
    ['05:17', `wasn't like obsessed with this set I`],
    ['05:20', `keep lighting it over and over and every`],
    ['05:21', `time someone comes to my house like oh`],
    ['05:23', `my god your house smells so good what is`],
    ['05:24', `that I'm like Honey Crisp apple candle`],
    ['05:27', `the Sun is golden Honey Crisp apple`],
    ['05:28', `blossom fresh sugarcane and again it's`],
    ['05:30', `with the central oils because one smells`],
    ['05:32', `really good this one is more of a`],
    ['05:33', `sweeter scent um but it's a really good`],
    ['05:35', `transitional candle like I said okay and`],
    ['05:37', `that's what the candle is burning the`],
    ['05:39', `next thing that I have are these`],
    ['05:40', `interactive journals that were actually`],
    ['05:43', `sent to me by a subscriber I think she`],
    ['05:45', `runs like a company it's called find`],
    ['05:47', `your magic but she basically I guess had`],
    ['05:49', `heard my podcast of like being overly`],
    ['05:52', `sensitive and I feel like people with`],
    ['05:54', `anxiety tend to be a little bit on the`],
    ['05:56', `sensitive side which kind of makes your`],
    ['05:58', `anxiety like deeper and stronger so she`],
    ['06:01', `sent me over these like journals that`],
    ['06:04', `she has in there interact that they're`],
    ['06:05', `like workbooks like this one says`],
    ['06:06', `planner for example but they're not like`],
    ['06:08', `dated planners like they're literally`],
    ['06:10', `just like worksheets but you put in`],
    ['06:12', `today's date so like you don't have to`],
    ['06:14', `like follow them verbatim every day`],
    ['06:16', `which I find it really hard to do with`],
    ['06:17', `planners and that's when I tend to throw`],
    ['06:19', `planners oh why is because I didn't`],
    ['06:20', `follow it and there's some empty pages`],
    ['06:22', `and I'm just OCD like that but this`],
    ['06:25', `one's really nice because again like you`],
    ['06:27', `just flip to it and then you put the`],
    ['06:28', `day's date every question is pretty much`],
    ['06:31', `different to which I really like I hate`],
    ['06:33', `when there's like worksheets that are`],
    ['06:34', `the same exact questions for every day`],
    ['06:36', `cuz I'm like I need to like work out my`],
    ['06:38', `brain you know`],
    ['06:39', `give me something there give me`],
    ['06:39', `something to think about so for example`],
    ['06:41', `I just flipped to a random page but it's`],
    ['06:43', `like today's date three things I want to`],
    ['06:44', `accomplish in life three things I'm`],
    ['06:46', `thankful for what gives me peace and`],
    ['06:48', `then the next day says what do I desire`],
    ['06:49', `three things I wish I had more of three`],
    ['06:52', `things that matter most and ideas like I`],
    ['06:54', `don't know it's really cool but it's`],
    ['06:56', `called the find your magic Journal and`],
    ['06:57', `planner start every day with a positive`],
    ['06:59', `thought and be productive I've been`],
    ['07:01', `doing this everyday and it honestly does`],
    ['07:03', `put me in a really good mood it doesn't`],
    ['07:04', `take long to fill out the quick little`],
    ['07:06', `bullet points you know but then she also`],
    ['07:08', `sent me this one this one to find your`],
    ['07:10', `magic heal your anxiety workbook so this`],
    ['07:12', `one I really really like this one's more`],
    ['07:13', `of a journal style so this one will`],
    ['07:15', `obviously take a lot of time but I do`],
    ['07:17', `this one more at nighttime whenever I'm`],
    ['07:19', `having just like random thoughts in my`],
    ['07:20', `head I just fill them out and again the`],
    ['07:22', `questions are all different so example`],
    ['07:24', `it's like what emotions are you feeling`],
    ['07:26', `write them down don't let them change`],
    ['07:28', `your day let it out write a letter today`],
    ['07:29', `to someone who has hurt you let it all`],
    ['07:31', `out it's just like very therapeutic and`],
    ['07:33', `I find it really easy to kind of just`],
    ['07:35', `incorporate into my day and I'm like`],
    ['07:36', `obsessed with it she was really sweet to`],
    ['07:38', `send this over definitely become part of`],
    ['07:40', `my daily routine so the next thing is`],
    ['07:42', `food-related don't we love food smart`],
    ['07:45', `sweets I've actually bought some of`],
    ['07:47', `these in a grocery haul recently and I`],
    ['07:50', `had I like I bought them and I was like`],
    ['07:52', `I'm gonna try them out I don't know if I`],
    ['07:53', `tried them on camera or not but I love`],
    ['07:55', `them like I craved sweets like no other`],
    ['07:58', `and sugars really bad for you basically`],
    ['08:01', `they are gummy bears but there's only`],
    ['08:04', `three grams of sugar per bag which is`],
    ['08:06', `completely crazy I think they use stevia`],
    ['08:08', `yeah stevia leaf um so it's non-gmo`],
    ['08:11', `gluten-free free from sugar alcohols`],
    ['08:13', `plant-based like high in fiber but you`],
    ['08:17', `would think they taste really gross but`],
    ['08:19', `they don't so they have like the gummy`],
    ['08:22', `bear ones taste like straight-up`],
    ['08:24', `real gummi bears but you're not getting`],
    ['08:26', `any sugar from them which is like really`],
    ['08:28', `freaking crazy`],
    ['08:29', `they also have like sour ones so they`],
    ['08:31', `have like sour gummy bears the little`],
    ['08:34', `sour guys so it's kind of like a take on`],
    ['08:38', `what it is they're like first they're`],
    ['08:40', `sweet now they're sour what are those`],
    ['08:42', `things called`],
    ['08:43', `sour patch kids and my favorite ones I'm`],
    ['08:46', `trying to save a bag to show you guys`],
    ['08:48', `but they were so good I just finished`],
    ['08:50', `them and I had three bags of each are`],
    ['08:51', `the peach rings`],
    ['08:52', `and then also the berry flavored got me`],
    ['08:55', `as they are so yeah I kind of I'm`],
    ['08:57', `craving one right now but let me show`],
    ['08:59', `you guys for example like this coming`],
    ['09:01', `the texture and everything is just like`],
    ['09:03', `a normal gummy bear and surprisingly it`],
    ['09:06', `tastes like a freaking gummy bear I need`],
    ['09:08', `to put these down because I will eat`],
    ['09:09', `them not so good I always found my`],
    ['09:12', `add-on hole fit but I guess you can guys`],
    ['09:15', `can get them at GNC too so if you guys`],
    ['09:17', `have one of those stores and I do highly`],
    ['09:18', `suggest picking up the berry flavor is`],
    ['09:21', `like the number one my favorite but have`],
    ['09:23', `you guys are into sour stuff tried the`],
    ['09:24', `sour gummy bears another kind of health`],
    ['09:26', `related product is probiotics so I`],
    ['09:29', `started taking these raw probiotics I`],
    ['09:31', `ended up picking these up because I`],
    ['09:33', `don't know I felt really down and I know`],
    ['09:36', `that like your gut is really really`],
    ['09:38', `important I think they call it like your`],
    ['09:39', `second brain or part of your brain or`],
    ['09:42', `whatever but basically it's like a focal`],
    ['09:43', `point in your health I definitely think`],
    ['09:45', `there's like a link to your mental`],
    ['09:47', `health as well and as you guys probably`],
    ['09:48', `know by now in the beginning of July`],
    ['09:51', `there at the end of July beginning of`],
    ['09:53', `August I was feeling really really down`],
    ['09:56', `not myself and I started taking the`],
    ['09:58', `probiotics I honestly feel so much more`],
    ['10:00', `energy I feel so much more positive I`],
    ['10:02', `don't know if it is this I'm just`],
    ['10:04', `assuming it is I usually take the`],
    ['10:06', `probiotics that were in the care of`],
    ['10:08', `packages those little personalized`],
    ['10:10', `vitamins and supplements which I liked`],
    ['10:13', `but I also really wanted to find like a`],
    ['10:14', `really strong powerful good sourced`],
    ['10:17', `probiotic like these ones you have to`],
    ['10:19', `leave in the fridge they are a little`],
    ['10:20', `bit more expensive but it's totally`],
    ['10:22', `worth it because it's your gut health`],
    ['10:23', `you know and I just like really feel the`],
    ['10:25', `difference and my gut my my mindset my`],
    ['10:29', `overall energy this one has 85 billion`],
    ['10:32', `live cultures 32 probiotic strands and`],
    ['10:35', `it's raw gluten free no binders fillers`],
    ['10:38', `or carriers they're vegetarian raw whole`],
    ['10:40', `food dietary supplements so I don't know`],
    ['10:43', `I find it hard to think of probiotics as`],
    ['10:45', `being alive if they're not refrigerated`],
    ['10:47', `so the one that I got obviously are the`],
    ['10:50', `Garden of Life raw probiotics so next`],
    ['10:54', `thing is this philosophy amazing grace`],
    ['10:58', `Magnolia perfume I'm in freakin love`],
    ['11:02', `with this I am like`],
    ['11:03', `one two like never venture off with`],
    ['11:05', `perfumes like once I find one that I`],
    ['11:07', `like I stick to and I've been using the`],
    ['11:09', `Juicy Couture what's it called the one`],
    ['11:13', `that everyone gets in its like pink juic`],
    ['11:15', `it's a coke juicy but I've been using`],
    ['11:16', `that for so many years and every time I`],
    ['11:18', `wear it sometimes like oh my god that`],
    ['11:19', `smells like my high school and I'm like`],
    ['11:20', `I probably should stop wearing this cuz`],
    ['11:22', `I feel like it's just such an old`],
    ['11:23', `perfume that everyone associated it as`],
    ['11:25', `like them as a kid like I have one like`],
    ['11:27', `that I used to wear this one called Noli`],
    ['11:29', `from PacSun all the time and when I when`],
    ['11:32', `I smell that smell it literally takes me`],
    ['11:34', `back to like being a kid but maybe`],
    ['11:37', `that's a sign that like you know you`],
    ['11:38', `need to venture away and like find`],
    ['11:40', `something new and I was actually sent`],
    ['11:41', `this by philosophy and it's so good I`],
    ['11:46', `don't know why I'm showing this to you`],
    ['11:47', `guys because you guys can't smell it I'm`],
    ['11:49', `showing you all smelly good things if`],
    ['11:51', `you guys like happen to run by a perfume`],
    ['11:54', `store or like a Sephora or something and`],
    ['11:55', `you see philosophy just give it us give`],
    ['11:57', `it a whiff give it a smell but I'm`],
    ['11:59', `telling you guys it smells so good I`],
    ['12:00', `like sweeter scents`],
    ['12:01', `I'm not really into like there's some`],
    ['12:04', `that are like very very strong`],
    ['12:05', `especially the ones that are like high`],
    ['12:07', `upscale kind of perfumes like I don't`],
    ['12:09', `know like big brands like Chanel and`],
    ['12:11', `stuff and I feel like those smell very`],
    ['12:13', `old ladylike but this one smells like`],
    ['12:14', `classy woman like it's not like you're a`],
    ['12:17', `kid but it's also not like you're a`],
    ['12:19', `fricking grandmother either it just`],
    ['12:20', `smells really good and it's so cute and`],
    ['12:22', `aesthetically pleasing I don't know even`],
    ['12:24', `how to describe descent let me see if I`],
    ['12:25', `can google it and see if they have like`],
    ['12:27', `a description of the scent because you`],
    ['12:29', `know how like the bath and Bodyworks`],
    ['12:30', `candles like they say what on the bottom`],
    ['12:33', `like what the sensor perfumes aren't`],
    ['12:35', `like that and the reviews are really`],
    ['12:36', `good too there's over 5,000 reviews and`],
    ['12:39', `it's a 4 out of 5 stars so other people`],
    ['12:42', `like it too and every time I wear this -`],
    ['12:44', `everyone's like you smell so good`],
    ['12:46', `like really it's soft and feminine so I`],
    ['12:49', `guess okay here's a fragrance notes the`],
    ['12:51', `top is bergamot the middles you get`],
    ['12:53', `blossoms and then the bases Musk's`],
    ['12:55', `whatever the that means but it`],
    ['12:57', `smells so good just trust me all right`],
    ['13:00', `next thing is my holy grail I am`],
    ['13:03', `obsessed with this I'm pretty sure I put`],
    ['13:05', `this in a favorites video already but`],
    ['13:07', `this is just goes to show how obsessed I`],
    ['13:09', `am with this product it's the sigma`],
    ['13:12', `brilliant shimmer cream this is how I`],
    ['13:15', `get my glowy skin`],
    ['13:17', `you see that glow it's always this I'm`],
    ['13:20', `gonna show you guys too this is what it`],
    ['13:23', `looks like it goes on so soft I just`],
    ['13:25', `kind of put some here on my finger and`],
    ['13:27', `I'll just rub it along my cheek can you`],
    ['13:31', `guys see how freakin glowy and beautiful`],
    ['13:34', `that is and it's so like naturally glowy`],
    ['13:36', `and there's like a hint of like pink so`],
    ['13:38', `it kind of acts as like a blush I'm like`],
    ['13:41', `obsessed I put it here on my cheeks on`],
    ['13:43', `my nose on my little what is this called`],
    ['13:47', `and then I also throw some underneath my`],
    ['13:49', `eyebrows and it just like it's so nice I`],
    ['13:53', `feel like all I need makeup wise is this`],
    ['13:56', `it makes your skin look so glowy so dewy`],
    ['13:59', `I'm obsessed with it I'm really am`],
    ['14:00', `obsessed with it I will never go to`],
    ['14:02', `anything else I don't think although I`],
    ['14:03', `have tried the Fenton highlighter and I`],
    ['14:05', `do like that but I really like the like`],
    ['14:07', `dewy look next product are my earrings`],
    ['14:11', `so these are from princess Polly they`],
    ['14:16', `have a hoop that goes behind your ear`],
    ['14:18', `and then like a little stub here that`],
    ['14:20', `goes above your ear and I just think`],
    ['14:22', `it's so different and cute and I just`],
    ['14:25', `really really really like these I'm`],
    ['14:28', `obsessed with them I've been wearing`],
    ['14:29', `them all the time I just think they're`],
    ['14:32', `very unique and different last but not`],
    ['14:34', `least is my music I've been obsessed`],
    ['14:36', `with music lately I think just cuz`],
    ['14:38', `Noah's gone in stuff that it just is`],
    ['14:39', `like my best friend that sounds so sad`],
    ['14:42', `I've been making so many different`],
    ['14:43', `playlist on Spotify and I just made one`],
    ['14:46', `recently called chillin and I'm gonna`],
    ['14:48', `pop it down below I'm not gonna like it`],
    ['14:50', `copyrighted like I didn't like it lit`],
    ['14:52', `with me video because that video like`],
    ['14:53', `yeah it was copyrighted so many`],
    ['14:55', `different times and I don't care so if`],
    ['14:57', `you guys want to like actually listen to`],
    ['14:58', `the music and stuff just go click on the`],
    ['15:00', `link or whatever and I'll pop that in`],
    ['15:02', `there in the meantime if you guys do`],
    ['15:03', `have a Spotify I've just been like`],
    ['15:05', `chilling music that just makes me very`],
    ['15:07', `chill calm but at the same time really`],
    ['15:10', `good flowy 5e music check out my`],
    ['15:12', `playlist called chillin and let me know`],
    ['15:14', `what you guys think so yeah I'm done`],
    ['15:17', `thank you guys so much for watching this`],
    ['15:19', `video I really appreciate it if you came`],
    ['15:21', `all the way to the end of the video I`],
    ['15:23', `love you guys`],
    ['15:24', `than anything y'all see guys honored`]
  ]),
  words: [
    { index: 0, id: '', meaning: [] },
    { index: 1, id: '', meaning: [] },
    { index: 2, id: '', meaning: [] },
    { index: 3, id: '', meaning: [] },
    { index: 4, id: '', meaning: [] },
    { index: 5, id: '', meaning: [] },
    { index: 6, id: '', meaning: [] },
    { index: 7, id: '', meaning: [] },
    { index: 8, id: '', meaning: [] },
    { index: 9, id: '', meaning: [] },
    { index: 10, id: '', meaning: [] },
    { index: 11, id: '', meaning: [] },
    { index: 12, id: '', meaning: [] },
    { index: 13, id: '', meaning: [] },
    { index: 14, id: '', meaning: [] },
    { index: 15, id: '', meaning: [] },
    { index: 16, id: '', meaning: [] },
    { index: 17, id: '', meaning: [] },
    { index: 18, id: '', meaning: [] },
    { index: 19, id: '', meaning: [] },
    { index: 20, id: '', meaning: [] },
    { index: 21, id: '', meaning: [] },
    { index: 22, id: '', meaning: [] },
    { index: 23, id: '', meaning: [] },
    { index: 24, id: '', meaning: [] },
    { index: 25, id: '', meaning: [] },
    { index: 26, id: '', meaning: [] },
    { index: 27, id: '', meaning: [] },
    { index: 28, id: '', meaning: [] },
    { index: 29, id: '', meaning: [] },
    { index: 30, id: '', meaning: [] },
    { index: 31, id: '', meaning: [] },
    { index: 32, id: '', meaning: [] },
    { index: 33, id: '', meaning: [] },
    { index: 34, id: '', meaning: [] },
    { index: 35, id: '', meaning: [] },
    { index: 36, id: '', meaning: [] },
    { index: 37, id: '', meaning: [] },
    { index: 38, id: '', meaning: [] },
    { index: 39, id: '', meaning: [] },
    { index: 40, id: '', meaning: [] },
    { index: 41, id: '', meaning: [] },
    { index: 42, id: '', meaning: [] },
    { index: 43, id: '', meaning: [] },
    { index: 44, id: '', meaning: [] },
    { index: 45, id: '', meaning: [] },
    { index: 46, id: '', meaning: [] },
    { index: 47, id: '', meaning: [] },
    { index: 48, id: '', meaning: [] },
    { index: 49, id: '', meaning: [] },
    { index: 50, id: '', meaning: [] },
    { index: 51, id: '', meaning: [] },
    { index: 52, id: '', meaning: [] },
    { index: 53, id: '', meaning: [] },
    { index: 54, id: '', meaning: [] },
    { index: 55, id: '', meaning: [] },
    { index: 56, id: '', meaning: [] },
    { index: 57, id: '', meaning: [] },
    { index: 58, id: '', meaning: [] },
    { index: 59, id: '', meaning: [] },
    { index: 60, id: '', meaning: [] },
    { index: 61, id: '', meaning: [] },
    { index: 62, id: '', meaning: [] },
    { index: 63, id: '', meaning: [] },
    { index: 64, id: '', meaning: [] },
    { index: 65, id: '', meaning: [] },
    { index: 66, id: '', meaning: [] },
    { index: 67, id: '', meaning: [] },
    { index: 68, id: '', meaning: [] },
    { index: 69, id: '', meaning: [] },
    { index: 70, id: '', meaning: [] },
    { index: 71, id: '', meaning: [] },
    { index: 72, id: '', meaning: [] },
    { index: 73, id: '', meaning: [] },
    { index: 74, id: '', meaning: [] },
    { index: 75, id: '', meaning: [] },
    { index: 76, id: '', meaning: [] },
    { index: 77, id: '', meaning: [] },
    { index: 78, id: '', meaning: [] },
    { index: 79, id: '', meaning: [] },
    { index: 80, id: '', meaning: [] },
    { index: 81, id: '', meaning: [] },
    { index: 82, id: '', meaning: [] },
    { index: 83, id: '', meaning: [] },
    { index: 84, id: '', meaning: [] },
    { index: 85, id: '', meaning: [] },
    { index: 86, id: '', meaning: [] },
    { index: 87, id: '', meaning: [] },
    { index: 88, id: '', meaning: [] },
    { index: 89, id: '', meaning: [] },
    { index: 90, id: '', meaning: [] },
    { index: 91, id: '', meaning: [] },
    { index: 92, id: '', meaning: [] },
    { index: 93, id: '', meaning: [] },
    { index: 94, id: '', meaning: [] },
    { index: 95, id: '', meaning: [] },
    { index: 96, id: '', meaning: [] },
    { index: 97, id: '', meaning: [] },
    { index: 98, id: '', meaning: [] },
    { index: 99, id: '', meaning: [] },
    { index: 100, id: '', meaning: [] },
    { index: 101, id: '', meaning: [] },
    { index: 102, id: '', meaning: [] },
    { index: 103, id: '', meaning: [] },
    { index: 104, id: '', meaning: [] },
    { index: 105, id: '', meaning: [] },
    { index: 106, id: '', meaning: [] },
    { index: 107, id: '', meaning: [] },
    { index: 108, id: '', meaning: [] },
    { index: 109, id: '', meaning: [] },
    { index: 110, id: '', meaning: [] },
    { index: 111, id: '', meaning: [] },
    { index: 112, id: '', meaning: [] },
    { index: 113, id: '', meaning: [] },
    { index: 114, id: '', meaning: [] },
    { index: 115, id: '', meaning: [] },
    { index: 116, id: '', meaning: [] },
    { index: 117, id: '', meaning: [] },
    { index: 118, id: '', meaning: [] },
    { index: 119, id: '', meaning: [] },
    { index: 120, id: '', meaning: [] },
    { index: 121, id: '', meaning: [] },
    { index: 122, id: '', meaning: [] },
    { index: 123, id: '', meaning: [] },
    { index: 124, id: '', meaning: [] },
    { index: 125, id: '', meaning: [] },
    { index: 126, id: '', meaning: [] },
    { index: 127, id: '', meaning: [] },
    { index: 128, id: '', meaning: [] },
    { index: 129, id: '', meaning: [] },
    { index: 130, id: '', meaning: [] },
    { index: 131, id: '', meaning: [] },
    { index: 132, id: '', meaning: [] },
    { index: 133, id: '', meaning: [] },
    { index: 134, id: '', meaning: [] },
    { index: 135, id: '', meaning: [] },
    { index: 136, id: '', meaning: [] },
    { index: 137, id: '', meaning: [] },
    { index: 138, id: '', meaning: [] },
    { index: 139, id: '', meaning: [] },
    { index: 140, id: '', meaning: [] },
    { index: 141, id: '', meaning: [] },
    { index: 142, id: '', meaning: [] },
    { index: 143, id: '', meaning: [] },
    { index: 144, id: '', meaning: [] },
    { index: 145, id: '', meaning: [] },
    { index: 146, id: '', meaning: [] },
    { index: 147, id: '', meaning: [] },
    { index: 148, id: '', meaning: [] },
    { index: 149, id: '', meaning: [] },
    { index: 150, id: '', meaning: [] },
    { index: 151, id: '', meaning: [] },
    { index: 152, id: '', meaning: [] },
    { index: 153, id: '', meaning: [] },
    { index: 154, id: '', meaning: [] },
    { index: 155, id: '', meaning: [] },
    { index: 156, id: '', meaning: [] },
    { index: 157, id: '', meaning: [] },
    { index: 158, id: '', meaning: [] },
    { index: 159, id: '', meaning: [] },
    { index: 160, id: '', meaning: [] },
    { index: 161, id: '', meaning: [] },
    { index: 162, id: '', meaning: [] },
    { index: 163, id: '', meaning: [] },
    { index: 164, id: '', meaning: [] },
    { index: 165, id: '', meaning: [] },
    { index: 166, id: '', meaning: [] },
    { index: 167, id: '', meaning: [] },
    { index: 168, id: '', meaning: [] },
    { index: 169, id: '', meaning: [] },
    { index: 170, id: '', meaning: [] },
    { index: 171, id: '', meaning: [] },
    { index: 172, id: '', meaning: [] },
    { index: 173, id: '', meaning: [] },
    { index: 174, id: '', meaning: [] },
    { index: 175, id: '', meaning: [] },
    { index: 176, id: '', meaning: [] },
    { index: 177, id: '', meaning: [] },
    { index: 178, id: '', meaning: [] },
    { index: 179, id: '', meaning: [] },
    { index: 180, id: '', meaning: [] },
    { index: 181, id: '', meaning: [] },
    { index: 182, id: '', meaning: [] },
    { index: 183, id: '', meaning: [] },
    { index: 184, id: '', meaning: [] },
    { index: 185, id: '', meaning: [] },
    { index: 186, id: '', meaning: [] },
    { index: 187, id: '', meaning: [] },
    { index: 188, id: '', meaning: [] },
    { index: 189, id: '', meaning: [] },
    { index: 190, id: '', meaning: [] },
    { index: 191, id: '', meaning: [] },
    { index: 192, id: '', meaning: [] },
    { index: 193, id: '', meaning: [] },
    { index: 194, id: '', meaning: [] },
    { index: 195, id: '', meaning: [] },
    { index: 196, id: '', meaning: [] },
    { index: 197, id: '', meaning: [] },
    { index: 198, id: '', meaning: [] },
    { index: 199, id: '', meaning: [] },
  ]
}