import { w } from './../utils/utils.js';

export default {
  title: `Productive Sunday. Cleaning, Grocery Haul, Weekly Planning, & Self Care`,
  type: 'movie',
  id: '538e557kk3xb3j2e',
  thumbnail: '538e511kk3xb3l56',
  header: `Productive Sunday. Cleaning, grocery haul, weekly planning, & self care.`,
  author: { name: "Renee Amberg", url: 'https://www.youtube.com/channel/UCwrck-lD9ERHLWxWDD8_uyA' },
  link: { name: 'Youtube', url: 'https://www.youtube.com/watch?v=ZdDI9EIOXek' },
  id: 'ZdDI9EIOXek',
  subtitles: new Map([
    ['00:15', `half these Sunday today today's gonna be`],
    ['00:17', `a Sunday vlog I have a lot of just`],
    ['00:20', `random stuff to do around my house today`],
    ['00:21', `I have to clean my apartment I have to`],
    ['00:23', `go grocery shopping I'm gonna be doing a`],
    ['00:25', `weekly plan with me I need to budget`],
    ['00:27', `just like a lot of just random stuff`],
    ['00:29', `before I get started into the vlog I`],
    ['00:31', `just want to say thank you so today's`],
    ['00:32', `sponsor which is hi smile so hi smile is`],
    ['00:35', `a teeth whitening system they recently`],
    ['00:37', `just launched a new and improved gel`],
    ['00:39', `based product based on like their past`],
    ['00:42', `consumer reviews and requests so I`],
    ['00:45', `thought I'd give it a try and give you`],
    ['00:46', `guys my honest opinion in terms of`],
    ['00:48', `self-care something that I do tend to do`],
    ['00:50', `on Sundays is teeth whitening so I'm`],
    ['00:52', `excited to try this out the thing that I`],
    ['00:53', `really like about it is that it doesn't`],
    ['00:55', `cause any pain or sensitivity which is`],
    ['00:57', `really hard to find in terms of like any`],
    ['00:59', `teeth whitening system now odds are when`],
    ['01:01', `you whiten your teeth you get a lot of`],
    ['01:03', `sensitivity and my teeth are so`],
    ['01:04', `sensitive to begin with so the fact that`],
    ['01:06', `they made the formula to not give you`],
    ['01:09', `sensitivity is something that really is`],
    ['01:10', `intriguing to me so let me show you guys`],
    ['01:12', `the Box real quick here is the box that`],
    ['01:15', `it comes with it comes with these two`],
    ['01:16', `kits so you have the teeth whitening gel`],
    ['01:19', `and then you have the teeth whitening`],
    ['01:21', `kits on the back it will tell you the`],
    ['01:24', `super easy to use instructions the key`],
    ['01:28', `ingredients are pomegranate chamomile`],
    ['01:30', `aloe vera and this fancy word and then`],
    ['01:35', `same goes with the back of this one`],
    ['01:37', `each gel contains two uses which is`],
    ['01:40', `pretty nice as well so here's the inside`],
    ['01:42', `of the kit the packaging is just`],
    ['01:43', `everything honestly like I said I'm`],
    ['01:45', `gonna be doing this when I do my`],
    ['01:46', `self-care which is like towards the end`],
    ['01:48', `of the day so when I start the actual`],
    ['01:50', `teeth whitening process I will take you`],
    ['01:52', `guys along with me and show you guys how`],
    ['01:54', `it works a little bit more but if you`],
    ['01:55', `are interested in it I will have`],
    ['01:57', `everything linked in the description I'm`],
    ['01:59', `pretty sure that launches today so`],
    ['02:00', `highly recommend to go get today just`],
    ['02:01', `because the new and improved high smile`],
    ['02:03', `is out for launch so today's the day to`],
    ['02:07', `get it yeah that's our sponsor for the`],
    ['02:08', `day it is currently 847 or 947 it was`],
    ['02:14', `daylight savings last night so`],
    ['02:15', `technically it's not it doesn't feel`],
    ['02:18', `like 8 o'clock or closer to 9:00 so I'm`],
    ['02:21', `gonna go ahead and just clean my`],
    ['02:22', `apartment it is an absolute disaster`],
    ['02:24', `area`],
    ['02:25', `haven't been home for a while I was in`],
    ['02:26', `Orlando I had Halloween I went to my`],
    ['02:28', `mom's so I've been kind of living out of`],
    ['02:30', `like a bag for the past two days and`],
    ['02:32', `everything in my house is just kind of`],
    ['02:34', `like right now so let's do that first to`],
    ['02:37', `clean my apartment`],
    ['02:40', `[Music]`],
    ['03:07', `[Music]`],
    ['03:24', `[Music]`],
    ['04:15', `[Music]`],
    ['05:12', `[Music]`],
    ['05:13', `[Applause]`],
    ['05:14', `[Music]`],
    ['06:08', `[Music]`],
    ['06:59', `[Music]`],
    ['07:42', `I just realized I was cleaning with my`],
    ['07:44', `black glasses on at this entire time I`],
    ['07:48', `pretty much cleaned all my okay did you`],
    ['07:50', `see that dust i pretty much cleaned my`],
    ['07:52', `entire apartment I got my new vacuum`],
    ['07:54', `robot guy and I have my laundry going`],
    ['07:57', `and I'm actually gonna be taking down`],
    ['07:59', `all of my Halloween decor it is November`],
    ['08:02', `2nd so it's time to take it down`],
    ['08:08', `[Music]`],
    ['08:29', `[Music]`],
    ['08:35', `alright guys I'm on my way to the`],
    ['08:37', `grocery store I have my bags for one if`],
    ['08:40', `you guys know anything about me and how`],
    ['08:42', `often I forgot my bags my hair is`],
    ['08:45', `looking real cute today yeah I'm on my`],
    ['08:46', `way to Whole Foods when I get back I`],
    ['08:48', `think I'm gonna share with you guys kind`],
    ['08:49', `of like a grocery haul all I have in my`],
    ['08:51', `fridge right now I am not even`],
    ['08:53', `exaggerating when I say like obviously`],
    ['08:55', `condiments like ketchup mustard I don't`],
    ['08:57', `even have ketchup mustard has to be me`],
    ['08:59', `last nothing about it I have salsa and I`],
    ['09:01', `have eggs in my fridge right now nice so`],
    ['09:05', `I need to go let's talk about my fridge`],
    ['09:07', `so I've got my pantry and prepare myself`],
    ['09:12', `for a healthy week it's also 11:11 I`],
    ['09:15', `thought I'd just share that with you`],
    ['09:16', `guys`],
    ['09:17', `alright you guys here is my colossal`],
    ['09:19', `grocery haul I'm going to start over`],
    ['09:22', `let's go to the left so I picked up some`],
    ['09:25', `ketchup and mustard because I ran out`],
    ['09:26', `this is the creamer that I put in my`],
    ['09:28', `espresso this is so good it's vanilla it`],
    ['09:31', `only has like three ingredients nonfat`],
    ['09:33', `milk creamer cane sugar and natural`],
    ['09:35', `flavor so not too bad we have some`],
    ['09:37', `almond milk the unsweetened original is`],
    ['09:39', `the one that I usually tend to gravitate`],
    ['09:40', `towards I picked up some smart sweets so`],
    ['09:44', `they didn't have the peach rings which I`],
    ['09:45', `was looking for but they had the fruity`],
    ['09:48', `gummies and then the sour patch kids`],
    ['09:49', `which I picked up for Noah he's a really`],
    ['09:51', `cool because they're gummi bears and`],
    ['09:53', `there's only three grams of sugar per`],
    ['09:54', `bag and they taste like real gummi bears`],
    ['09:56', `it's a good like snack if you're craving`],
    ['09:58', `any sweets I also picked up some walnuts`],
    ['10:00', `some really Elizabeth Amy's granola you`],
    ['10:03', `guys know I'm like obsessed with this`],
    ['10:04', `he's only 6 grams of sugar it's really`],
    ['10:06', `good very crunchy and just filled with`],
    ['10:08', `like tons of like superfoods this brand`],
    ['10:10', `has the best nuts they have cashews`],
    ['10:13', `pecans I know what it is about them but`],
    ['10:15', `they just have the best taste I guess`],
    ['10:17', `like I don't know if it to the packaging`],
    ['10:19', `or what but this brand is so good but I`],
    ['10:21', `picked up there`],
    ['10:22', `toss down chips they're kind of like`],
    ['10:24', `plantain chips they're really really`],
    ['10:25', `good`],
    ['10:26', `back over here we have some peanut`],
    ['10:27', `butter they ran out of the what's the`],
    ['10:30', `one that I usually get I don't even`],
    ['10:31', `remember but they ran out of the one`],
    ['10:33', `that I usually get so I had to get this`],
    ['10:34', `one I just got the one that just has`],
    ['10:36', `peanuts like no sugar or salt added I`],
    ['10:38', `picked up this marinara sauce I love`],
    ['10:41', `this stuff picked up some lentil soup`],
    ['10:43', `and then I picked up some lentil veggie`],
    ['10:44', `soup no and I have been like loving`],
    ['10:46', `lentil soup and it's kind`],
    ['10:47', `getting chillier believe it or not here`],
    ['10:49', `in Florida if you just add a little bit`],
    ['10:51', `of lemon drops into the soup it just`],
    ['10:52', `changes the whole flavor it is so so`],
    ['10:55', `good I got some asparagus some broccoli`],
    ['10:58', `some berries blueberries and raspberries`],
    ['11:00', `I got two avocados some Honey Crisp`],
    ['11:04', `apples an onion a red pepper some red`],
    ['11:07', `skin potatoes we got some Xenia I got`],
    ['11:11', `dr. Zvi which is like the take on dr.`],
    ['11:13', `pepper and then cola which is like Coke`],
    ['11:15', `again this is made with stevia so`],
    ['11:18', `there's like no sugar no calories or`],
    ['11:20', `anything but it's also like naturally`],
    ['11:22', `flavored so it's not unhealthy in any`],
    ['11:23', `way I don't think it's like the best for`],
    ['11:26', `you but it's definitely not like the`],
    ['11:27', `worst I picked up some pasta this is`],
    ['11:29', `just the gluten free pasta it's brown`],
    ['11:31', `rice and then I picked up a ancient`],
    ['11:32', `harvest macaroni style noodles this one`],
    ['11:35', `is corn and quinoa what else do we have`],
    ['11:37', `we have some mozzarella this yogurt I've`],
    ['11:41', `been loving it's the ciggies just plain`],
    ['11:43', `I just put a little bit of manuka honey`],
    ['11:45', `some berries and nuts in it it's really`],
    ['11:47', `really good for a nice yogurt parfait`],
    ['11:50', `I got some halo top again very low sugar`],
    ['11:53', `made with stevia and whatever numbers in`],
    ['11:56', `the front of the halo top is the amount`],
    ['11:58', `of calories in the whole entire pint so`],
    ['12:00', `it's like a healthier option if you're`],
    ['12:01', `craving ice cream and it actually tastes`],
    ['12:03', `really good I'm not a fan of the`],
    ['12:04', `dairy-free I feel like it has a weird`],
    ['12:06', `aftertaste so I picked up strawberry and`],
    ['12:08', `the chocolate which are my favorite`],
    ['12:11', `flavors we have a ton of bananas I need`],
    ['12:13', `these to like go ripe so I can throw`],
    ['12:15', `them in my freezer for some smoothie`],
    ['12:16', `bowls because I don't have any frozen`],
    ['12:18', `bananas and that's a problem here in my`],
    ['12:20', `house I got some wild caught salmon this`],
    ['12:23', `should last me like a month maybe two I`],
    ['12:25', `just take one out if I'm gonna have it`],
    ['12:28', `for dinner it's a good option because it`],
    ['12:29', `doesn't go bad and it's wild-caught so`],
    ['12:31', `not farm-raised healthy this is Noah's`],
    ['12:34', `he wanted me to pick him up some wings`],
    ['12:35', `so I got him wings he puts them in the`],
    ['12:37', `airfryer and it literally is the most`],
    ['12:40', `amazing thing ever you just throw in`],
    ['12:42', `anything honestly you can do frozen`],
    ['12:46', `fries regular fries chicken steak`],
    ['12:48', `poultry fish like we have literally put`],
    ['12:51', `everything in here you don't have oil`],
    ['12:53', `you press a button and it's done in like`],
    ['12:54', `two seconds and it fries it and it's`],
    ['12:57', `healthy it's amazing so he's gonna end`],
    ['12:59', `up putting like these probably in the`],
    ['13:00', `airfryer`],
    ['13:01', `and then I got some organic ground`],
    ['13:02', `turkey so that is my grocery haul for`],
    ['13:06', `Sunday this should last me probably two`],
    ['13:08', `to three weeks I might run out of like`],
    ['13:10', `little things like almond milk but this`],
    ['13:12', `lasts me pretty much a good while it`],
    ['13:14', `seems like a lot but again like I said I`],
    ['13:17', `legit`],
    ['13:18', `only have salsa eggs and water in my`],
    ['13:22', `fridge right now so this is much-needed`],
    ['13:24', `I'm gonna put this away and then I think`],
    ['13:26', `I'm gonna do some self-care I'm actually`],
    ['13:29', `going to do my weekly planning before I`],
    ['13:32', `do my self-care that way when I do my`],
    ['13:34', `self-care I can just relax and I'll have`],
    ['13:35', `to worry about doing anything else so`],
    ['13:37', `I'm gonna go into my computer real quick`],
    ['13:38', `and do a quick like weekly update I do`],
    ['13:42', `this every single Sunday to kind of just`],
    ['13:43', `prep for the week and that way on Monday`],
    ['13:45', `I kind of already have my week spread`],
    ['13:47', `out and I have an idea like what I'm`],
    ['13:49', `gonna be doing for the week kind of`],
    ['13:50', `explain this in a previous vlog but`],
    ['13:52', `basically I got this like yellow notepad`],
    ['13:56', `and I write out the Wednesday`],
    ['13:58', `friday-sunday videos that I have for the`],
    ['14:00', `week so one of them is gonna be a sit`],
    ['14:02', `down video which is gonna be every`],
    ['14:03', `Wednesday one of them is going to be a`],
    ['14:05', `more highly produced video which is`],
    ['14:06', `going to be every single Friday and then`],
    ['14:08', `I have a vlog so for example this is`],
    ['14:10', `what I had last week`],
    ['14:12', `this was my sit down video this was my`],
    ['14:17', `scheduled more highly produced video and`],
    ['14:19', `this was my vlog so now we're starting`],
    ['14:22', `with a new week I have actually four`],
    ['14:24', `videos going up this week we have the`],
    ['14:27', `Wednesday sit down video the vlog the`],
    ['14:32', `bonus video which is going to be this`],
    ['14:33', `video hello and then we have a more`],
    ['14:36', `highly produced video as well but I`],
    ['14:38', `didn't write that down yet so I'm going`],
    ['14:39', `to kind of prep them out and what I do`],
    ['14:41', `is I just kind of do the research of`],
    ['14:42', `like the talking point so I'm going to`],
    ['14:44', `be doing for the videos that way I have`],
    ['14:46', `them all kind of planned out and then`],
    ['14:48', `I'm going to put them into my Google`],
    ['14:50', `Calendar I kind of broke up the videos I`],
    ['14:54', `guess onto two tasks if you will so the`],
    ['14:57', `first is obviously the filming portion`],
    ['14:59', `and then we have the editing and`],
    ['15:01', `uploading portion I used to do editing`],
    ['15:03', `and uploading separate but honestly`],
    ['15:04', `whenever I add it I tend to upload so it`],
    ['15:06', `they're like edit upload dates and then`],
    ['15:09', `we also have like obviously the day that`],
    ['15:10', `it goes live and the time that it goes`],
    ['15:12', `so I'll put that into my schedule and`],
    ['15:15', `what I do is I will put them on the top`],
    ['15:17', `of my Google Calendar like let me show`],
    ['15:19', `you an example and then I'll just plug`],
    ['15:22', `in a time kind of like when you walk`],
    ['15:24', `into work I kind of like just track to`],
    ['15:26', `see how long it takes me I'm gonna be`],
    ['15:28', `doing this so the end of the year to`],
    ['15:29', `kind of just see a realistic timeframe`],
    ['15:31', `of how long videos take to like film and`],
    ['15:33', `edit and all that stuff and that way I`],
    ['15:35', `can plan out my schedule better for this`],
    ['15:37', `week I have all the stuff to do up here`],
    ['15:39', `just not allotted to a time and then for`],
    ['15:41', `example today like I will edit how long`],
    ['15:44', `it took me to edit the vlog and how long`],
    ['15:45', `it took me to film the vlog how long it`],
    ['15:48', `took me to upload by the end of the week`],
    ['15:49', `it kind of just looks like this so`],
    ['15:51', `that's like how I've been doing my`],
    ['15:53', `scheduling in terms of my videos but I`],
    ['15:56', `know every single day what I will be`],
    ['15:58', `doing and then I will be plugging in`],
    ['16:00', `like the days at my videos they'll live`],
    ['16:02', `so every Sunday I typically put up a`],
    ['16:04', `video around 9:00 a.m. I actually did`],
    ['16:08', `8:30 this morning so I'm gonna change`],
    ['16:11', `that but usually every Sunday I post at`],
    ['16:15', `9:00 a.m. and then Wednesday and Friday`],
    ['16:18', `I post at noon and I'm in Eastern`],
    ['16:20', `Standard Time so if you guys didn't know`],
    ['16:23', `that now you do`],
    ['16:24', `and then I will reach out to the`],
    ['16:26', `sponsors if I have any for the week like`],
    ['16:28', `if I'm gonna be filming or uploading any`],
    ['16:30', `of the length of sponsored videos I will`],
    ['16:32', `update the sponsorship people that I'm`],
    ['16:34', `in contact with to kind of just give`],
    ['16:36', `them an update of when I'll be filming`],
    ['16:37', `and when I will be editing and uploading`],
    ['16:39', `the video and give them a time as to`],
    ['16:41', `when I'm gonna have the final product`],
    ['16:42', `delivered to them just to kind of keep`],
    ['16:44', `them updated and make sure that they're`],
    ['16:46', `aware of what's going on and I can get`],
    ['16:48', `approved in time and all that stuff and`],
    ['16:50', `then after that according to my filming`],
    ['16:52', `schedule I will plug in my workout`],
    ['16:54', `schedule I set you guys down please`],
    ['16:56', `excuse like the washer this is just my`],
    ['16:59', `Sunday so again if you guys watched my`],
    ['17:01', `event I think I was like mid-november`],
    ['17:02', `planning with me I did I post a note of`],
    ['17:04', `all the workouts and stuff that I'm`],
    ['17:06', `gonna be doing for the week and I just`],
    ['17:07', `cross them out as I go but I added in`],
    ['17:09', `two rough days but that kind of messed`],
    ['17:11', `with me cuz I didn't know exactly how`],
    ['17:12', `much I should be doing every single day`],
    ['17:13', `at the end of the week having to do like`],
    ['17:16', `four different things in one day and`],
    ['17:17', `that's just like so unrealistic so I`],
    ['17:19', `kind of grouped them all together now`],
    ['17:20', `instead my cluster them together into`],
    ['17:22', `seven days and`],
    ['17:24', `now I know how to realistically get this`],
    ['17:26', `done throughout the week without feeling`],
    ['17:28', `like stressed or overwhelmed so any day`],
    ['17:30', `I just put wonder 7 this doesn't have to`],
    ['17:32', `be Monday Tuesday Wednesday it's just`],
    ['17:34', `whatever day I'm feeling one day will be`],
    ['17:36', `cardio and abs one day will be cardio`],
    ['17:37', `and legs one will be rest one will be`],
    ['17:39', `rest when will be yoga and abs one will`],
    ['17:42', `be back in arms and the other one will`],
    ['17:43', `be yoga and depending on which day I do`],
    ['17:46', `them I'll just cross them up as I go but`],
    ['17:47', `this is gonna help ensure that I get`],
    ['17:49', `everything done by the end of the week`],
    ['17:50', `but I also include the two rest days and`],
    ['17:52', `also get done everything that I want to`],
    ['17:54', `get done so I'm gonna get that stuff`],
    ['17:55', `done and just prep out my week throw`],
    ['17:59', `some music on and just like have myself`],
    ['18:01', `a planning`],
    ['18:05', `[Music]`],
    ['18:55', `so I ended up doing my budget as well`],
    ['18:58', `because it's the third and I honestly`],
    ['19:00', `didn't have time to do it because it was`],
    ['19:02', `like Halloween and then I went to`],
    ['19:04', `Orlando so I ended up doing it today and`],
    ['19:06', `just kind of filled in my budget feel`],
    ['19:09', `like there was something more that I had`],
    ['19:10', `to say but I'm pretty sure that's it um`],
    ['19:12', `but now I have everything kind of`],
    ['19:15', `scheduled for the week which makes me so`],
    ['19:18', `happy I'm going to start the self-care`],
    ['19:21', `now I deserve this I'm going to take a`],
    ['19:24', `bath read and say some stuff I've been`],
    ['19:28', `reading this one super slow because it`],
    ['19:31', `is so good and the information like I`],
    ['19:33', `feel like I definitely want to take it`],
    ['19:35', `in it's definitely gonna be a book and I`],
    ['19:36', `like reread I think it has been so good`],
    ['19:39', `every time I like read it I write down a`],
    ['19:41', `whole section on my notes and like`],
    ['19:43', `things I want to remember and things`],
    ['19:44', `that I kind of like had aha moments with`],
    ['19:46', `so I'm taking it really slowly but it's`],
    ['19:47', `just so good I'm gonna focus on getting`],
    ['19:50', `this read by the end of the week and`],
    ['19:52', `then I'll start my Hunger Games book I'm`],
    ['19:56', `gonna show you guys how I make a yogurt`],
    ['19:57', `parfait and I've been like obsessed with`],
    ['20:00', `lately so I have my ciggies plain yogurt`],
    ['20:03', `so we have some berries whatever berries`],
    ['20:04', `you like I like blueberries raspberries`],
    ['20:06', `and then I have some nuts`],
    ['20:07', `sliced almonds with the outer shells`],
    ['20:10', `still on because I was like the most`],
    ['20:11', `nutritious part and then walnuts is like`],
    ['20:14', `one of the healthiest things you can`],
    ['20:15', `ever put in your body it's so good for`],
    ['20:16', `you and then I top it with some manuka`],
    ['20:18', `honey to sweeten manuka honey is`],
    ['20:20', `probably the best honey ever for you out`],
    ['20:23', `there but I'm not gonna lie it is super`],
    ['20:25', `expensive and I'm super lucky that nella`],
    ['20:27', `gets it from Europe and it's totally`],
    ['20:29', `worth it honestly the investment just`],
    ['20:31', `Google like the manuka honey benefits`],
    ['20:33', `and it's just amazing so this is just`],
    ['20:35', `also healthy for you so I usually do`],
    ['20:37', `about like two really hefty scoops of`],
    ['20:41', `yogurt about that much and then I'll`],
    ['20:43', `throw in my berries a little handful of`],
    ['20:45', `each this many blueberries I love`],
    ['20:48', `blueberries like literally a handful pop`],
    ['20:50', `it with something`],
    ['20:52', `I actually put like cranberries in it`],
    ['20:55', `last time and I was gonna good but I`],
    ['20:56', `don't have any leftover it's just a`],
    ['21:00', `little bit of almonds and then the best`],
    ['21:05', `parts the manuka honey this honestly`],
    ['21:07', `tastes way better than honey as well`],
    ['21:09', `like I and not a fan of honey that much`],
    ['21:11', `but this is delicious so I just take a`],
    ['21:14', `fork literally drizzle it on there like`],
    ['21:17', `this then you have yourself a delicious`],
    ['21:19', `yogurt parfait so usually every Sunday`],
    ['21:26', `and Wednesday I will do like this self`],
    ['21:28', `tanner`],
    ['21:29', `I just exfoliated my skin I'm fresh out`],
    ['21:31', `of the shower and I have just a plain`],
    ['21:34', `body lotion and then the Tanner that`],
    ['21:37', `I've been using is the Isle of paradise`],
    ['21:39', `self tanning drops these are amazing you`],
    ['21:41', `literally just like put lotion on your`],
    ['21:43', `body and put two two like four drops our`],
    ['21:46', `body part of these self tanning drops`],
    ['21:49', `and just apply them in with your lotion`],
    ['21:51', `and it makes for a really nice tan and`],
    ['21:53', `it doesn't get on any of your sheets or`],
    ['21:54', `anything so it's really cool obviously`],
    ['21:57', `I'm not gonna do my whole body in front`],
    ['21:59', `of the camera because I'll do my arm`],
    ['22:01', `with you guys I'll show you guys how I`],
    ['22:03', `do my arm so I do like about two pumps`],
    ['22:06', `just regular lotion I'm just gonna do`],
    ['22:08', `two drops of the Tanner you just do one`],
    ['22:11', `to mix it in with your lotion just put`],
    ['22:16', `on your body and you got yourself a nice`],
    ['22:19', `tan it's pretty cool my favorite part is`],
    ['22:21', `it just like doesn't smell it doesn't`],
    ['22:25', `get on your sheets like I used to have`],
    ['22:28', `to do like with the mousse I'd have to`],
    ['22:30', `put a whole set of new sheets on my bed`],
    ['22:32', `because it would just stain all of my`],
    ['22:34', `sheets so it's pretty much how you do it`],
    ['22:37', `I'm gonna do my body and then I'm gonna`],
    ['22:39', `start I'll show you guys how I do like`],
    ['22:41', `the whitening of my teeth`],
    ['22:43', `time for the teeth whitening so I'm`],
    ['22:45', `gonna be using high smile but they give`],
    ['22:48', `you like this yellow thing which kind of`],
    ['22:51', `freaks me out seeing what color I am I`],
    ['22:53', `feel like I'm between a three and a four`],
    ['22:55', `and then you can use this to kind of see`],
    ['22:57', `and track your teeth wait`],
    ['22:59', `because it'll show results attach the`],
    ['23:02', `mouth tray to the LED light so I'm just`],
    ['23:04', `attaching this apply 1/4 of the gel lid`],
    ['23:08', `and they have like the numbers here on`],
    ['23:10', `the side so it's really easy to see 1/4`],
    ['23:13', `which is and 1/4 on the bottom waiting`],
    ['23:22', `for 10 minutes and repeat daily all`],
    ['23:25', `right`],
    ['23:37', `I also like that you don't like moles`],
    ['23:40', `the mouthpiece I've had teeth whitening`],
    ['23:42', `kits before where like you really have`],
    ['23:44', `to mold the mouthpiece to your mouth and`],
    ['23:46', `you'd like boil the water and say this`],
    ['23:48', `one process this took like 10 minutes I`],
    ['23:52', `was so quick super doable every night so`],
    ['23:55', `I'm gonna keep doing that and well like`],
    ['23:58', `keep you guys updated and like blogs and`],
    ['24:00', `online and stuff but um if you guys want`],
    ['24:03', `to check them out and do the challenge`],
    ['24:05', `with me I believe everything in the`],
    ['24:07', `description box this kind of concludes`],
    ['24:08', `my Sunday I pretty much do that`],
    ['24:11', `clean go grocery shopping plan my week`],
    ['24:14', `do some self-care and just kind of take`],
    ['24:17', `it really easy it is currently 3:30`],
    ['24:20', `but because daylight savings time it`],
    ['24:22', `feels like it's 4:30 because yesterday`],
    ['24:24', `it would have been 4:30 so what I like`],
    ['24:26', `to do now is just kind of wind down I'll`],
    ['24:28', `like read a little bit I'm gonna be`],
    ['24:29', `editing some videos and just kind of`],
    ['24:31', `preparing for tomorrow and yeah that`],
    ['24:33', `concludes this vlog I hope you guys`],
    ['24:35', `enjoyed it thanks for talking along with`],
    ['24:37', `me on the Sunday I love you guys so much`],
    ['24:39', `and I'll see you guys all`],
    ['24:41', `thank you`]
  ]),
  words: [
    { index: 0, id: '', meaning: [] },
    { index: 1, id: '', meaning: [] },
    { index: 2, id: '', meaning: [] },
    { index: 3, id: '', meaning: [] },
    { index: 4, id: '', meaning: [] },
    { index: 5, id: '', meaning: [] },
    { index: 6, id: '', meaning: [] },
    { index: 7, id: '', meaning: [] },
    { index: 8, id: '', meaning: [] },
    { index: 9, id: '', meaning: [] },
    { index: 10, id: '', meaning: [] },
    { index: 11, id: '', meaning: [] },
    { index: 12, id: '', meaning: [] },
    { index: 13, id: '', meaning: [] },
    { index: 14, id: '', meaning: [] },
    { index: 15, id: '', meaning: [] },
    { index: 16, id: '', meaning: [] },
    { index: 17, id: '', meaning: [] },
    { index: 18, id: '', meaning: [] },
    { index: 19, id: '', meaning: [] },
    { index: 20, id: '', meaning: [] },
    { index: 21, id: '', meaning: [] },
    { index: 22, id: '', meaning: [] },
    { index: 23, id: '', meaning: [] },
    { index: 24, id: '', meaning: [] },
    { index: 25, id: '', meaning: [] },
    { index: 26, id: '', meaning: [] },
    { index: 27, id: '', meaning: [] },
    { index: 28, id: '', meaning: [] },
    { index: 29, id: '', meaning: [] },
    { index: 30, id: '', meaning: [] },
    { index: 31, id: '', meaning: [] },
    { index: 32, id: '', meaning: [] },
    { index: 33, id: '', meaning: [] },
    { index: 34, id: '', meaning: [] },
    { index: 35, id: '', meaning: [] },
    { index: 36, id: '', meaning: [] },
    { index: 37, id: '', meaning: [] },
    { index: 38, id: '', meaning: [] },
    { index: 39, id: '', meaning: [] },
    { index: 40, id: '', meaning: [] },
    { index: 41, id: '', meaning: [] },
    { index: 42, id: '', meaning: [] },
    { index: 43, id: '', meaning: [] },
    { index: 44, id: '', meaning: [] },
    { index: 45, id: '', meaning: [] },
    { index: 46, id: '', meaning: [] },
    { index: 47, id: '', meaning: [] },
    { index: 48, id: '', meaning: [] },
    { index: 49, id: '', meaning: [] },
    { index: 50, id: '', meaning: [] },
    { index: 51, id: '', meaning: [] },
    { index: 52, id: '', meaning: [] },
    { index: 53, id: '', meaning: [] },
    { index: 54, id: '', meaning: [] },
    { index: 55, id: '', meaning: [] },
    { index: 56, id: '', meaning: [] },
    { index: 57, id: '', meaning: [] },
    { index: 58, id: '', meaning: [] },
    { index: 59, id: '', meaning: [] },
    { index: 60, id: '', meaning: [] },
    { index: 61, id: '', meaning: [] },
    { index: 62, id: '', meaning: [] },
    { index: 63, id: '', meaning: [] },
    { index: 64, id: '', meaning: [] },
    { index: 65, id: '', meaning: [] },
    { index: 66, id: '', meaning: [] },
    { index: 67, id: '', meaning: [] },
    { index: 68, id: '', meaning: [] },
    { index: 69, id: '', meaning: [] },
    { index: 70, id: '', meaning: [] },
    { index: 71, id: '', meaning: [] },
    { index: 72, id: '', meaning: [] },
    { index: 73, id: '', meaning: [] },
    { index: 74, id: '', meaning: [] },
    { index: 75, id: '', meaning: [] },
    { index: 76, id: '', meaning: [] },
    { index: 77, id: '', meaning: [] },
    { index: 78, id: '', meaning: [] },
    { index: 79, id: '', meaning: [] },
    { index: 80, id: '', meaning: [] },
    { index: 81, id: '', meaning: [] },
    { index: 82, id: '', meaning: [] },
    { index: 83, id: '', meaning: [] },
    { index: 84, id: '', meaning: [] },
    { index: 85, id: '', meaning: [] },
    { index: 86, id: '', meaning: [] },
    { index: 87, id: '', meaning: [] },
    { index: 88, id: '', meaning: [] },
    { index: 89, id: '', meaning: [] },
    { index: 90, id: '', meaning: [] },
    { index: 91, id: '', meaning: [] },
    { index: 92, id: '', meaning: [] },
    { index: 93, id: '', meaning: [] },
    { index: 94, id: '', meaning: [] },
    { index: 95, id: '', meaning: [] },
    { index: 96, id: '', meaning: [] },
    { index: 97, id: '', meaning: [] },
    { index: 98, id: '', meaning: [] },
    { index: 99, id: '', meaning: [] },
    { index: 100, id: '', meaning: [] },
    { index: 101, id: '', meaning: [] },
    { index: 102, id: '', meaning: [] },
    { index: 103, id: '', meaning: [] },
    { index: 104, id: '', meaning: [] },
    { index: 105, id: '', meaning: [] },
    { index: 106, id: '', meaning: [] },
    { index: 107, id: '', meaning: [] },
    { index: 108, id: '', meaning: [] },
    { index: 109, id: '', meaning: [] },
    { index: 110, id: '', meaning: [] },
    { index: 111, id: '', meaning: [] },
    { index: 112, id: '', meaning: [] },
    { index: 113, id: '', meaning: [] },
    { index: 114, id: '', meaning: [] },
    { index: 115, id: '', meaning: [] },
    { index: 116, id: '', meaning: [] },
    { index: 117, id: '', meaning: [] },
    { index: 118, id: '', meaning: [] },
    { index: 119, id: '', meaning: [] },
    { index: 120, id: '', meaning: [] },
    { index: 121, id: '', meaning: [] },
    { index: 122, id: '', meaning: [] },
    { index: 123, id: '', meaning: [] },
    { index: 124, id: '', meaning: [] },
    { index: 125, id: '', meaning: [] },
    { index: 126, id: '', meaning: [] },
    { index: 127, id: '', meaning: [] },
    { index: 128, id: '', meaning: [] },
    { index: 129, id: '', meaning: [] },
    { index: 130, id: '', meaning: [] },
    { index: 131, id: '', meaning: [] },
    { index: 132, id: '', meaning: [] },
    { index: 133, id: '', meaning: [] },
    { index: 134, id: '', meaning: [] },
    { index: 135, id: '', meaning: [] },
    { index: 136, id: '', meaning: [] },
    { index: 137, id: '', meaning: [] },
    { index: 138, id: '', meaning: [] },
    { index: 139, id: '', meaning: [] },
    { index: 140, id: '', meaning: [] },
    { index: 141, id: '', meaning: [] },
    { index: 142, id: '', meaning: [] },
    { index: 143, id: '', meaning: [] },
    { index: 144, id: '', meaning: [] },
    { index: 145, id: '', meaning: [] },
    { index: 146, id: '', meaning: [] },
    { index: 147, id: '', meaning: [] },
    { index: 148, id: '', meaning: [] },
    { index: 149, id: '', meaning: [] },
    { index: 150, id: '', meaning: [] },
    { index: 151, id: '', meaning: [] },
    { index: 152, id: '', meaning: [] },
    { index: 153, id: '', meaning: [] },
    { index: 154, id: '', meaning: [] },
    { index: 155, id: '', meaning: [] },
    { index: 156, id: '', meaning: [] },
    { index: 157, id: '', meaning: [] },
    { index: 158, id: '', meaning: [] },
    { index: 159, id: '', meaning: [] },
    { index: 160, id: '', meaning: [] },
    { index: 161, id: '', meaning: [] },
    { index: 162, id: '', meaning: [] },
    { index: 163, id: '', meaning: [] },
    { index: 164, id: '', meaning: [] },
    { index: 165, id: '', meaning: [] },
    { index: 166, id: '', meaning: [] },
    { index: 167, id: '', meaning: [] },
    { index: 168, id: '', meaning: [] },
    { index: 169, id: '', meaning: [] },
    { index: 170, id: '', meaning: [] },
    { index: 171, id: '', meaning: [] },
    { index: 172, id: '', meaning: [] },
    { index: 173, id: '', meaning: [] },
    { index: 174, id: '', meaning: [] },
    { index: 175, id: '', meaning: [] },
    { index: 176, id: '', meaning: [] },
    { index: 177, id: '', meaning: [] },
    { index: 178, id: '', meaning: [] },
    { index: 179, id: '', meaning: [] },
    { index: 180, id: '', meaning: [] },
    { index: 181, id: '', meaning: [] },
    { index: 182, id: '', meaning: [] },
    { index: 183, id: '', meaning: [] },
    { index: 184, id: '', meaning: [] },
    { index: 185, id: '', meaning: [] },
    { index: 186, id: '', meaning: [] },
    { index: 187, id: '', meaning: [] },
    { index: 188, id: '', meaning: [] },
    { index: 189, id: '', meaning: [] },
    { index: 190, id: '', meaning: [] },
    { index: 191, id: '', meaning: [] },
    { index: 192, id: '', meaning: [] },
    { index: 193, id: '', meaning: [] },
    { index: 194, id: '', meaning: [] },
    { index: 195, id: '', meaning: [] },
    { index: 196, id: '', meaning: [] },
    { index: 197, id: '', meaning: [] },
    { index: 198, id: '', meaning: [] },
    { index: 199, id: '', meaning: [] },
  ]
}