
import { w, header, paragraph, list } from './../utils/utils.js';

export default {
  title: "Blue Zones Are Places Where People Live Much Longer Than Average",
  type: 'article',
  id: '538e53v0k4r6v1w7',
  thumbnail: '538e56wgk4r6v3x2',
  header: `Blue zones are places where people live much longer than average.`,
  author: { name: 'Reuben Westmaas' },
  link: { name: 'Curiosity', url: 'https://curiosity.com/topics/blue-zones-are-places-where-people-live-much-longer-than-average-curiosity/' },
  text: [
    paragraph(`Humans have been searching for the fountain of youth ever since we climbed down from the trees. We'd say that it's an impossible dream, except that there are so many communities around the world that seem to have found their own sources of anti-aging. What makes these so-called "Blue Zones" so healthy, and what can we learn from them?`),
    header(`The Bluest Places on Earth`),
    paragraph(`So what is a Blue Zone? In broad terms, it's a place where people live to be 100 at extraordinarily high rates, have an extraordinarily average high life expectancy, or an extraordinarily low mortality rate for middle-aged people. When National Geographic explorer Dan Buettner first started looking into these strangely healthy places, he began to note certain similarities that tied them all together. But where are they?`),
    paragraph(`You'll find them all over the world. The first spot that grabbed Buettner's attention was Sardinia, a large Italian island just north of Tunisia. It has the most men over 100 in the world — everywhere else, there are five centenarian women for every centenarian man, but on Sardinia, the ratio is 1-to-1.`),
    paragraph(`The Japanese island of Okinawa is another Blue Zone, and Okinawan women have the longest average life expectancy of anyone on the planet. Back in the Mediterranean, elderly Greek residents of Ikaria live eight years longer than average and have a much lower dementia rate on average. And across the ocean in the Americas, you've got plenty of centenarians in the Nicoya Peninsula in Costa Rica, and Loma Linda, California, is home to an Adventist community that lives longer than anyone else in the United States.`),
    paragraph(`One thing that immediately pops out is how close all of these places are to the ocean. It's probably not very surprising, therefore, that Buettner links a seafood-oriented diet with a longer lifespan. But it isn't just about eating fish — many of these places have strangely similar eating habits, including heaping helpings of legumes and enjoying a (moderate) amount of wine. There's more, too, but we can't go over every aspect of diet here. Check out Buettner's "The Blue Zone Solution" for a dietary prescription from the oldest nonnas on the planet.`),
    header(`Living Your Bluest Life`),
    paragraph(`But how you eat isn't the only thing that determines how long you'll live. In fact, Buettner and his associates have instead identified a series of behavioral and environmental factors at play that keep people in these few places healthier, longer. Here are a few of the key ingredients:`),
    list([
      `Natural Motion. Blue Zoners aren't taking up Jazzercise; they're staying active naturally by keeping up physical work they've done their whole lives.`,
      `Purpose. In virtually every Blue Zone, elderly people are encouraged to stay active and support the community — retirement may not be very good for you!`,
      `Down Shift. While stress is a universal part of life, no matter what color your zone, Blue Zones often have cultural practices designed to lessen stress and blow off steam.`,
      `80% Rule. Okinawans specifically live by this directive: Stop eating when you are 80 percent full. It's an easy way to hit the sweet spot between "enough" and "too much."`,
      `Vegetarian Habits. Almost all of the places on the Blue Zone list have a long tradition of favoring vegetarian cuisine (even if they aren't strictly vegetarian).`,
    ]),
    paragraph(`That's just the first half of the rules, but it all makes a certain sense. Healthy living, healthy motion, and a healthy sense of purpose — it all adds up to a long and happy life.`),
  ],
  words: [
    { index: 0, id: '', meaning: [] },
    { index: 1, id: '', meaning: [] },
    { index: 2, id: '', meaning: [] },
    { index: 3, id: '', meaning: [] },
    { index: 4, id: '', meaning: [] },
    { index: 5, id: '', meaning: [] },
    { index: 6, id: '', meaning: [] },
    { index: 7, id: '', meaning: [] },
    { index: 8, id: '', meaning: [] },
    { index: 9, id: '', meaning: [] },
    { index: 10, id: '', meaning: [] },
    { index: 11, id: '', meaning: [] },
    { index: 12, id: '', meaning: [] },
    { index: 13, id: '', meaning: [] },
    { index: 14, id: '', meaning: [] },
    { index: 15, id: '', meaning: [] },
    { index: 16, id: '', meaning: [] },
    { index: 17, id: '', meaning: [] },
    { index: 18, id: '', meaning: [] },
    { index: 19, id: '', meaning: [] },
    { index: 20, id: '', meaning: [] },
    { index: 21, id: '', meaning: [] },
    { index: 22, id: '', meaning: [] },
    { index: 23, id: '', meaning: [] },
    { index: 24, id: '', meaning: [] },
    { index: 25, id: '', meaning: [] },
    { index: 26, id: '', meaning: [] },
    { index: 27, id: '', meaning: [] },
    { index: 28, id: '', meaning: [] },
    { index: 29, id: '', meaning: [] },
    { index: 30, id: '', meaning: [] },
    { index: 31, id: '', meaning: [] },
    { index: 32, id: '', meaning: [] },
    { index: 33, id: '', meaning: [] },
    { index: 34, id: '', meaning: [] },
    { index: 35, id: '', meaning: [] },
    { index: 36, id: '', meaning: [] },
    { index: 37, id: '', meaning: [] },
    { index: 38, id: '', meaning: [] },
    { index: 39, id: '', meaning: [] },
    { index: 40, id: '', meaning: [] },
    { index: 41, id: '', meaning: [] },
    { index: 42, id: '', meaning: [] },
    { index: 43, id: '', meaning: [] },
    { index: 44, id: '', meaning: [] },
    { index: 45, id: '', meaning: [] },
    { index: 46, id: '', meaning: [] },
    { index: 47, id: '', meaning: [] },
    { index: 48, id: '', meaning: [] },
    { index: 49, id: '', meaning: [] },
    { index: 50, id: '', meaning: [] },
    { index: 51, id: '', meaning: [] },
    { index: 52, id: '', meaning: [] },
    { index: 53, id: '', meaning: [] },
    { index: 54, id: '', meaning: [] },
    { index: 55, id: '', meaning: [] },
    { index: 56, id: '', meaning: [] },
    { index: 57, id: '', meaning: [] },
    { index: 58, id: '', meaning: [] },
    { index: 59, id: '', meaning: [] },
    { index: 60, id: '', meaning: [] },
    { index: 61, id: '', meaning: [] },
    { index: 62, id: '', meaning: [] },
    { index: 63, id: '', meaning: [] },
    { index: 64, id: '', meaning: [] },
    { index: 65, id: '', meaning: [] },
    { index: 66, id: '', meaning: [] },
    { index: 67, id: '', meaning: [] },
    { index: 68, id: '', meaning: [] },
    { index: 69, id: '', meaning: [] },
    { index: 70, id: '', meaning: [] },
    { index: 71, id: '', meaning: [] },
    { index: 72, id: '', meaning: [] },
    { index: 73, id: '', meaning: [] },
    { index: 74, id: '', meaning: [] },
    { index: 75, id: '', meaning: [] },
    { index: 76, id: '', meaning: [] },
    { index: 77, id: '', meaning: [] },
    { index: 78, id: '', meaning: [] },
    { index: 79, id: '', meaning: [] },
    { index: 80, id: '', meaning: [] },
    { index: 81, id: '', meaning: [] },
    { index: 82, id: '', meaning: [] },
    { index: 83, id: '', meaning: [] },
    { index: 84, id: '', meaning: [] },
    { index: 85, id: '', meaning: [] },
    { index: 86, id: '', meaning: [] },
    { index: 87, id: '', meaning: [] },
    { index: 88, id: '', meaning: [] },
    { index: 89, id: '', meaning: [] },
    { index: 90, id: '', meaning: [] },
    { index: 91, id: '', meaning: [] },
    { index: 92, id: '', meaning: [] },
    { index: 93, id: '', meaning: [] },
    { index: 94, id: '', meaning: [] },
    { index: 95, id: '', meaning: [] },
    { index: 96, id: '', meaning: [] },
    { index: 97, id: '', meaning: [] },
    { index: 98, id: '', meaning: [] },
    { index: 99, id: '', meaning: [] },
    { index: 100, id: '', meaning: [] },
    { index: 101, id: '', meaning: [] },
    { index: 102, id: '', meaning: [] },
    { index: 103, id: '', meaning: [] },
    { index: 104, id: '', meaning: [] },
  ]
};