
import { w, header, paragraph, list } from './../utils/utils.js';

export default {
  title: "5 Etiquette Tips To Help You Thrive In Any Social Situation",
  type: 'article',
  id: '538e54nck51ccd4u',
  thumbnail: '538e52l4k51ccf3t',
  header: `5 etiquette tips to help you thrive in any social situation.`,
  author: { name: 'Cody Gough' },
  link: { name: 'Curiosity', url: 'https://curiosity.com/topics/5-etiquette-tips-to-help-you-thrive-in-any-social-situation-curiosity/' },
  text: [
    paragraph(`Have you ever wondered how to make someone feel more welcome or appreciated (including yourself)? Believe it or not, etiquette wasn't invented to confuse or irritate people. On the contrary: proper etiquette is about being comfortable in any situation. Knowing what rules to follow can make everyone's life easier – including your own!`),
    paragraph(`We've seen colossal changes in technology and social equality over the last few decades, and some old-fashioned etiquette is outdated (ladies, when is the last time a man kissed your hand when introduced?). Fortunately, there are a few guidelines you can follow to know how to act around others.`),
    header(`Polite Conversation`),
    paragraph(`When you aren't sure what to do, refer to the fundamental rules of etiquette. So what are they? The Emily Post Institute divides etiquette into two parts.`),
    paragraph(`The first part is manners, which can change depending on when and where you are in the world (for example, in different countries, you might greet people with a handshake, a kiss on both cheeks, or a bow).`),
    paragraph(`The second part refers to the three principles of etiquette: consideration, respect, and honesty.`),
    paragraph(`While traditions around the world vary, there are sure-fire ways to handle yourself anywhere you go:`),
    header(`1. Make eye contact and greet everyone at the beginning of an interaction`),
    paragraph(`Have you ever checked out at a grocery store or coffee shop, or hopped in the back seat of a taxi, and barely grunted a "hello" to the cashier or driver? Remember that it's a human being who is about to make your coffee or drive you somewhere – and people are social creatures. "Those little things like asking 'how are you doing' or eye contact... will make someone's day," etiquette expert Jihan Murray-Smith told us on the Curiosity Podcast. Some cashiers would be happy with as little as eye contact and a smile, but asking "how is your day going?" can go a long way toward improving someone's day.`),
    header(`2. Stand when greeting someone who is joining your group`),
    paragraph(`When you stand, you literally rise to the occasion of showing respect to a newcomer. This rule pertains to any social situation, whether you're drinking at a bar with friends, dining out in a business meeting, welcoming relatives at home for a holiday meal, or seeing your date enter the bar or restaurant where you're sitting. Oh, and ladies, don't get too comfortable in your seat: with the changing roles of women in the workplace, this area of etiquette has been revised over the years to include all genders – not just men. That means you should stand when others arrive, too.`),
    header(`3. Always bring a gift as a guest in someone's home`),
    paragraph(`To make a good impression (and increase the chances you'll be invited again), "never show up to someone's home empty-handed," Murray-Smith told us. "Even when my friends say 'don't bring anything, just bring yourself,' I bring something. Flowers for the host to say thank you for hosting us... if my friend enjoys wine, I'll pick up a couple of bottles... if I know there are guests there who don't drink, I'll pick up some sparkling juice or cider... a box of chocolates, a candle... something for the host to enjoy. Just bring something."`),
    header(`Prepare For A Rude Awakening`),
    header(`4. Put your phone away when you're socializing with others`),
    paragraph(`"Texting anarchy" is how Emily Post's great-granddaughter, Cindy Post Senning, describes our use of phones today. "People are texting everywhere," she told the New York Times. And in her book, "Emily Post's Table Manners for Kids," she takes a hard line against texting in social situations – even with family.`),
    paragraph(`"If you pull out your cell phone, that reads as 'the person I'm talking to on my phone is more important than you,' and you're right in front of me," Murray-Smith agreed. Even if your immediate family has no problem with phone use at the dinner table, it's worth remembering that at some point, you or your kids will likely be in a social situation where others do take issue. And bringing that bad habit into a meeting, class, or business function could cost you more than friends.`),
    paragraph(`If you need to check your phone because you're expecting an emergency, then explain your situation to your party, and check sparingly. Ignore non-urgent messages, and excuse yourself from the table if you need to take a call.`),
    header(`5. It's not your job to correct someone else's etiquette`),
    paragraph(`So what if someone is rude to you? "We're all going through different things. I'm not saying that's a pass for people be to be rude," Murray-Smith told us. "However, being thoughtful and considerate is understanding that we all are human beings and we all are going through things at home... extending some compassion for one another is very important. If someone is being a little rude or snippy with you, I would not take that as an opportunity to say something rude or mean. I would smile and just say 'I hope you have a good day.' Someone has to be the bigger person."`)
  ],
  words: [
    { index: 0, id: '', meaning: [] },
    { index: 1, id: '', meaning: [] },
    { index: 2, id: '', meaning: [] },
    { index: 3, id: '', meaning: [] },
    { index: 4, id: '', meaning: [] },
    { index: 5, id: '', meaning: [] },
    { index: 6, id: '', meaning: [] },
    { index: 7, id: '', meaning: [] },
    { index: 8, id: '', meaning: [] },
    { index: 9, id: '', meaning: [] },
    { index: 10, id: '', meaning: [] },
    { index: 11, id: '', meaning: [] },
    { index: 12, id: '', meaning: [] },
    { index: 13, id: '', meaning: [] },
    { index: 14, id: '', meaning: [] },
    { index: 15, id: '', meaning: [] },
    { index: 16, id: '', meaning: [] },
    { index: 17, id: '', meaning: [] },
    { index: 18, id: '', meaning: [] },
    { index: 19, id: '', meaning: [] },
    { index: 20, id: '', meaning: [] },
    { index: 21, id: '', meaning: [] },
    { index: 22, id: '', meaning: [] },
    { index: 23, id: '', meaning: [] },
    { index: 24, id: '', meaning: [] },
    { index: 25, id: '', meaning: [] },
    { index: 26, id: '', meaning: [] },
    { index: 27, id: '', meaning: [] },
    { index: 28, id: '', meaning: [] },
    { index: 29, id: '', meaning: [] },
    { index: 30, id: '', meaning: [] },
    { index: 31, id: '', meaning: [] },
    { index: 32, id: '', meaning: [] },
    { index: 33, id: '', meaning: [] },
    { index: 34, id: '', meaning: [] },
    { index: 35, id: '', meaning: [] },
    { index: 36, id: '', meaning: [] },
    { index: 37, id: '', meaning: [] },
    { index: 38, id: '', meaning: [] },
    { index: 39, id: '', meaning: [] },
    { index: 40, id: '', meaning: [] },
    { index: 41, id: '', meaning: [] },
    { index: 42, id: '', meaning: [] },
    { index: 43, id: '', meaning: [] },
    { index: 44, id: '', meaning: [] },
    { index: 45, id: '', meaning: [] },
    { index: 46, id: '', meaning: [] },
    { index: 47, id: '', meaning: [] },
    { index: 48, id: '', meaning: [] },
    { index: 49, id: '', meaning: [] },
    { index: 50, id: '', meaning: [] },
    { index: 51, id: '', meaning: [] },
    { index: 52, id: '', meaning: [] },
    { index: 53, id: '', meaning: [] },
    { index: 54, id: '', meaning: [] },
    { index: 55, id: '', meaning: [] },
    { index: 56, id: '', meaning: [] },
    { index: 57, id: '', meaning: [] },
    { index: 58, id: '', meaning: [] },
    { index: 59, id: '', meaning: [] },
    { index: 60, id: '', meaning: [] },
    { index: 61, id: '', meaning: [] },
    { index: 62, id: '', meaning: [] },
    { index: 63, id: '', meaning: [] },
    { index: 64, id: '', meaning: [] },
    { index: 65, id: '', meaning: [] },
    { index: 66, id: '', meaning: [] },
    { index: 67, id: '', meaning: [] },
    { index: 68, id: '', meaning: [] },
    { index: 69, id: '', meaning: [] },
    { index: 70, id: '', meaning: [] },
    { index: 71, id: '', meaning: [] },
    { index: 72, id: '', meaning: [] },
    { index: 73, id: '', meaning: [] },
    { index: 74, id: '', meaning: [] },
    { index: 75, id: '', meaning: [] },
    { index: 76, id: '', meaning: [] },
    { index: 77, id: '', meaning: [] },
    { index: 78, id: '', meaning: [] },
    { index: 79, id: '', meaning: [] },
    { index: 80, id: '', meaning: [] },
    { index: 81, id: '', meaning: [] },
    { index: 82, id: '', meaning: [] },
    { index: 83, id: '', meaning: [] },
    { index: 84, id: '', meaning: [] },
    { index: 85, id: '', meaning: [] },
    { index: 86, id: '', meaning: [] },
    { index: 87, id: '', meaning: [] },
    { index: 88, id: '', meaning: [] },
    { index: 89, id: '', meaning: [] },
    { index: 90, id: '', meaning: [] },
    { index: 91, id: '', meaning: [] },
    { index: 92, id: '', meaning: [] },
    { index: 93, id: '', meaning: [] },
    { index: 94, id: '', meaning: [] },
    { index: 95, id: '', meaning: [] },
    { index: 96, id: '', meaning: [] },
    { index: 97, id: '', meaning: [] },
    { index: 98, id: '', meaning: [] },
    { index: 99, id: '', meaning: [] },
    { index: 100, id: '', meaning: [] },
    { index: 101, id: '', meaning: [] },
    { index: 102, id: '', meaning: [] },
    { index: 103, id: '', meaning: [] },
    { index: 104, id: '', meaning: [] },
  ]
};