
import { w, header, paragraph, list } from './../utils/utils.js';

export default {
  title: "Good Anxiety Can Help You Get Things Done",
  type: 'article',
  id: '538e54ugk5053nby',
  thumbnail: '538e54s4k5053pr6',
  header: `Good anxiety can help you get things done.`,
  author: { name: 'Reuben Westmaas' },
  link: { name: 'Curiosity', url: 'https://curiosity.com/topics/good-anxiety-can-help-you-get-things-done-curiosity/' },
  text: [
    paragraph(`Do you worry a lot? Obsess over the details? Live in fear of a never-ending parade of deadlines? Sign yourself up for way too many obligations, then chew your fingernails over the fact that you aren't doing enough? The bad news is, you are experiencing a form of anxiety. The good news is, it might be making you a powerhouse of productivity.`),
    header(`Making the Most of a Monkey Mind`),
    paragraph(`A new study published in the Journal of Individual Differences has described a spectrum of anxiety sufferers and mapped how their emotional state affected their motivation. They found that anxiety could be a powerful motivator — for some. For others, it had the opposite effect, causing depression and a major dropoff in productivity. The study was inspired by corresponding author Juliane Strack's observation that in some situations, negative emotions such as anxiety can be as powerful a driver as the pursuit of positive emotions. Luckily, the study also served to prove her point. Anxiety doesn't always result in a negative outcome. It might be good for your career, too.`),
    paragraph(`Most interestingly, those with what researchers called "high anxiety-motivation" were found to have higher grades and be more satisfied at work than anxious people with low anxiety-motivation. In other words, the ability to be motivated by anxiety could completely offset many of the negative side effects traditionally associated with it. So if you find yourself feeling overwhelmed with your workload, it might help to try to twist that feeling towards better motivation. After all, if you tackle it quickly, you won't be so overwhelmed afterward!`),
    header(`Calming the Storm`),
    paragraph(`Although anxiety can have a positive impact on your well-being, it's not something that you necessarily want to let grow unchecked. After all, anxiety has been linked to such issues as short-term memory loss and an inability to concentrate. If you've been plagued with recurring anxiety problems, you might try this three-pronged strategy to calm it when things get too loud:`),
    list([
      `Exercise. Yes, you've heard it before, but it's true. Cardio exercises such as jogging release endorphins and leave you feeling relaxed and accomplished.`,
      `Breath Training. Hyperventilation is one of the main symptoms of an anxiety attack, and it only makes the problem worse. Try slowing the rhythm down to about 15 seconds per breath.`,
      `Sensory Stimulation. Though too many digital screens can exacerbate anxiety, watching a silly TV show or something else can help you give you a quick release.`
    ])
  ],
  words: [
    { index: 0, id: '', meaning: [] },
    { index: 1, id: '', meaning: [] },
    { index: 2, id: '', meaning: [] },
    { index: 3, id: '', meaning: [] },
    { index: 4, id: '', meaning: [] },
    { index: 5, id: '', meaning: [] },
    { index: 6, id: '', meaning: [] },
    { index: 7, id: '', meaning: [] },
    { index: 8, id: '', meaning: [] },
    { index: 9, id: '', meaning: [] },
    { index: 10, id: '', meaning: [] },
    { index: 11, id: '', meaning: [] },
    { index: 12, id: '', meaning: [] },
    { index: 13, id: '', meaning: [] },
    { index: 14, id: '', meaning: [] },
    { index: 15, id: '', meaning: [] },
    { index: 16, id: '', meaning: [] },
    { index: 17, id: '', meaning: [] },
    { index: 18, id: '', meaning: [] },
    { index: 19, id: '', meaning: [] },
    { index: 20, id: '', meaning: [] },
    { index: 21, id: '', meaning: [] },
    { index: 22, id: '', meaning: [] },
    { index: 23, id: '', meaning: [] },
    { index: 24, id: '', meaning: [] },
    { index: 25, id: '', meaning: [] },
    { index: 26, id: '', meaning: [] },
    { index: 27, id: '', meaning: [] },
    { index: 28, id: '', meaning: [] },
    { index: 29, id: '', meaning: [] },
    { index: 30, id: '', meaning: [] },
    { index: 31, id: '', meaning: [] },
    { index: 32, id: '', meaning: [] },
    { index: 33, id: '', meaning: [] },
    { index: 34, id: '', meaning: [] },
    { index: 35, id: '', meaning: [] },
    { index: 36, id: '', meaning: [] },
    { index: 37, id: '', meaning: [] },
    { index: 38, id: '', meaning: [] },
    { index: 39, id: '', meaning: [] },
    { index: 40, id: '', meaning: [] },
    { index: 41, id: '', meaning: [] },
    { index: 42, id: '', meaning: [] },
    { index: 43, id: '', meaning: [] },
    { index: 44, id: '', meaning: [] },
    { index: 45, id: '', meaning: [] },
    { index: 46, id: '', meaning: [] },
    { index: 47, id: '', meaning: [] },
    { index: 48, id: '', meaning: [] },
    { index: 49, id: '', meaning: [] },
    { index: 50, id: '', meaning: [] },
    { index: 51, id: '', meaning: [] },
    { index: 52, id: '', meaning: [] },
    { index: 53, id: '', meaning: [] },
    { index: 54, id: '', meaning: [] },
    { index: 55, id: '', meaning: [] },
    { index: 56, id: '', meaning: [] },
    { index: 57, id: '', meaning: [] },
    { index: 58, id: '', meaning: [] },
    { index: 59, id: '', meaning: [] },
    { index: 60, id: '', meaning: [] },
    { index: 61, id: '', meaning: [] },
    { index: 62, id: '', meaning: [] },
    { index: 63, id: '', meaning: [] },
    { index: 64, id: '', meaning: [] },
    { index: 65, id: '', meaning: [] },
    { index: 66, id: '', meaning: [] },
    { index: 67, id: '', meaning: [] },
    { index: 68, id: '', meaning: [] },
    { index: 69, id: '', meaning: [] },
    { index: 70, id: '', meaning: [] },
    { index: 71, id: '', meaning: [] },
    { index: 72, id: '', meaning: [] },
    { index: 73, id: '', meaning: [] },
    { index: 74, id: '', meaning: [] },
    { index: 75, id: '', meaning: [] },
    { index: 76, id: '', meaning: [] },
    { index: 77, id: '', meaning: [] },
    { index: 78, id: '', meaning: [] },
    { index: 79, id: '', meaning: [] },
    { index: 80, id: '', meaning: [] },
    { index: 81, id: '', meaning: [] },
    { index: 82, id: '', meaning: [] },
    { index: 83, id: '', meaning: [] },
    { index: 84, id: '', meaning: [] },
    { index: 85, id: '', meaning: [] },
    { index: 86, id: '', meaning: [] },
    { index: 87, id: '', meaning: [] },
    { index: 88, id: '', meaning: [] },
    { index: 89, id: '', meaning: [] },
    { index: 90, id: '', meaning: [] },
    { index: 91, id: '', meaning: [] },
    { index: 92, id: '', meaning: [] },
    { index: 93, id: '', meaning: [] },
    { index: 94, id: '', meaning: [] },
    { index: 95, id: '', meaning: [] },
    { index: 96, id: '', meaning: [] },
    { index: 97, id: '', meaning: [] },
    { index: 98, id: '', meaning: [] },
    { index: 99, id: '', meaning: [] },
    { index: 100, id: '', meaning: [] },
    { index: 101, id: '', meaning: [] },
    { index: 102, id: '', meaning: [] },
    { index: 103, id: '', meaning: [] },
    { index: 104, id: '', meaning: [] },
  ]
};