
import { w, header, paragraph, list } from './../utils/utils.js';

export default {
  title: "Need A Lawyer? Artificial Intelligence Can Help",
  type: 'article',
  id: '538e53e4k4r9o6ow',
  thumbnail: '538e56s4k4r9o8la',
  header: `Need a lawyer? Artificial intelligence can help.`,
  author: { name: 'Ashley Hamer' },
  link: { name: 'Curiosity', url: 'https://curiosity.com/topics/need-a-lawyer-artificial-intelligence-can-help-curiosity/' },
  text: [
    paragraph(`Of all the jobs robots might one day take over, there are some that have always seemed off limits. For example, artificial intelligence could never gain the creativity to be an artist or a musician (except it has), learn the human emotions necessary to write comedy (sorry, that too), or possess the analytical thinking you need to become a lawyer. Well, every one of those has proven to be false. In fact, AI has been helping humans with their minor legal inconveniences for several years now. It's only going to get more advanced from here.`),
    header(`Lawyer-Bot, at Your Service`),
    paragraph(`Before you go petitioning to make an AI the next Supreme Court Justice, you should know that we're still miles away from a computerized Jack McCoy, an Atticus Finch-bot, or a Mecha-Matlock. Right now, AI law assistants are centered mostly on simple, straightforward legal matters, the kinds that require some complicated paperwork but don't exactly delve into the essence of human ethics. But just because the tasks are simple doesn't mean these bots aren't changing the world.`),
    paragraph(`Hiring a lawyer is expensive; battling an issue out in court, even more so. In a perfect world, many legal matters, from renter's rights to immigration to bankruptcy, could be handled with 30 minutes of paperwork and perhaps a minor fee. But most people need to pay for a lawyer just to get that far. Even divorces don't need to be as expensive as they are now. According to The Wall Street Journal, 95 percent of divorces are uncontested but still cost up to $10,000, mostly because of attorney's fees.`),
    paragraph(`"About 80 percent of people who need legal help can't afford it," developer Joshua Browder told the Wall Street Journal, "and it's really strange that nothing has been done for consumers in this area." Luckily, Browder and other innovators are trying to fix that.`),
    header(`I'm Afraid I Can't Do That, Your Honor`),
    paragraph(`As a 17-year-old Stanford computer science major, Joshua Browder created the AI bot DoNotPay as a way to help his friends battle parking tickets — the bane of many a college student's existence. The free bot simply automates the process for appealing tickets, asking a series of questions about your case so it can generate a letter to file with your school or city parking office. It soon went viral and has helped nearly half a million people save nearly $11 million in fines. Browder has since added more functionality to DoNotPay, and it can now help users demand compensation for delayed airline flights, receive government housing assistance, or even sue EquiFax for its recent data breach.`),
    paragraph(`DoNotPay's next target is divorce, something that the AI built by Cambridge University law students, called LawBot, is already tackling. It doesn't yet file the necessary paperwork for you, but it does let you explain your unique situation and then educate you on what to expect when you do talk to a lawyer. Meanwhile, a number of law firms are already using IBM's AI ROSS to handle the mundane research and background tasks necessary for court cases, tasks that would usually be delegated to a junior attorney. While these technologies are simply making the legal process more streamlined and automated, who knows — we could one day see a bot trained to argue in the courtroom.`),
  ],
  words: [
    { index: 0, id: '', meaning: [] },
    { index: 1, id: '', meaning: [] },
    { index: 2, id: '', meaning: [] },
    { index: 3, id: '', meaning: [] },
    { index: 4, id: '', meaning: [] },
    { index: 5, id: '', meaning: [] },
    { index: 6, id: '', meaning: [] },
    { index: 7, id: '', meaning: [] },
    { index: 8, id: '', meaning: [] },
    { index: 9, id: '', meaning: [] },
    { index: 10, id: '', meaning: [] },
    { index: 11, id: '', meaning: [] },
    { index: 12, id: '', meaning: [] },
    { index: 13, id: '', meaning: [] },
    { index: 14, id: '', meaning: [] },
    { index: 15, id: '', meaning: [] },
    { index: 16, id: '', meaning: [] },
    { index: 17, id: '', meaning: [] },
    { index: 18, id: '', meaning: [] },
    { index: 19, id: '', meaning: [] },
    { index: 20, id: '', meaning: [] },
    { index: 21, id: '', meaning: [] },
    { index: 22, id: '', meaning: [] },
    { index: 23, id: '', meaning: [] },
    { index: 24, id: '', meaning: [] },
    { index: 25, id: '', meaning: [] },
    { index: 26, id: '', meaning: [] },
    { index: 27, id: '', meaning: [] },
    { index: 28, id: '', meaning: [] },
    { index: 29, id: '', meaning: [] },
    { index: 30, id: '', meaning: [] },
    { index: 31, id: '', meaning: [] },
    { index: 32, id: '', meaning: [] },
    { index: 33, id: '', meaning: [] },
    { index: 34, id: '', meaning: [] },
    { index: 35, id: '', meaning: [] },
    { index: 36, id: '', meaning: [] },
    { index: 37, id: '', meaning: [] },
    { index: 38, id: '', meaning: [] },
    { index: 39, id: '', meaning: [] },
    { index: 40, id: '', meaning: [] },
    { index: 41, id: '', meaning: [] },
    { index: 42, id: '', meaning: [] },
    { index: 43, id: '', meaning: [] },
    { index: 44, id: '', meaning: [] },
    { index: 45, id: '', meaning: [] },
    { index: 46, id: '', meaning: [] },
    { index: 47, id: '', meaning: [] },
    { index: 48, id: '', meaning: [] },
    { index: 49, id: '', meaning: [] },
    { index: 50, id: '', meaning: [] },
    { index: 51, id: '', meaning: [] },
    { index: 52, id: '', meaning: [] },
    { index: 53, id: '', meaning: [] },
    { index: 54, id: '', meaning: [] },
    { index: 55, id: '', meaning: [] },
    { index: 56, id: '', meaning: [] },
    { index: 57, id: '', meaning: [] },
    { index: 58, id: '', meaning: [] },
    { index: 59, id: '', meaning: [] },
    { index: 60, id: '', meaning: [] },
    { index: 61, id: '', meaning: [] },
    { index: 62, id: '', meaning: [] },
    { index: 63, id: '', meaning: [] },
    { index: 64, id: '', meaning: [] },
    { index: 65, id: '', meaning: [] },
    { index: 66, id: '', meaning: [] },
    { index: 67, id: '', meaning: [] },
    { index: 68, id: '', meaning: [] },
    { index: 69, id: '', meaning: [] },
    { index: 70, id: '', meaning: [] },
    { index: 71, id: '', meaning: [] },
    { index: 72, id: '', meaning: [] },
    { index: 73, id: '', meaning: [] },
    { index: 74, id: '', meaning: [] },
    { index: 75, id: '', meaning: [] },
    { index: 76, id: '', meaning: [] },
    { index: 77, id: '', meaning: [] },
    { index: 78, id: '', meaning: [] },
    { index: 79, id: '', meaning: [] },
    { index: 80, id: '', meaning: [] },
    { index: 81, id: '', meaning: [] },
    { index: 82, id: '', meaning: [] },
    { index: 83, id: '', meaning: [] },
    { index: 84, id: '', meaning: [] },
    { index: 85, id: '', meaning: [] },
    { index: 86, id: '', meaning: [] },
    { index: 87, id: '', meaning: [] },
    { index: 88, id: '', meaning: [] },
    { index: 89, id: '', meaning: [] },
    { index: 90, id: '', meaning: [] },
    { index: 91, id: '', meaning: [] },
    { index: 92, id: '', meaning: [] },
    { index: 93, id: '', meaning: [] },
    { index: 94, id: '', meaning: [] },
    { index: 95, id: '', meaning: [] },
    { index: 96, id: '', meaning: [] },
    { index: 97, id: '', meaning: [] },
    { index: 98, id: '', meaning: [] },
    { index: 99, id: '', meaning: [] },
    { index: 100, id: '', meaning: [] },
    { index: 101, id: '', meaning: [] },
    { index: 102, id: '', meaning: [] },
    { index: 103, id: '', meaning: [] },
    { index: 104, id: '', meaning: [] },
  ]
};