
import { w, header, paragraph, list } from './../utils/utils.js';

export default {
  title: "Moravec's Paradox Is Why The Easy Stuff Is Hardest For Artificial Intelligence",
  type: 'article',
  id: '538e514kk4r970tw',
  thumbnail: '538e55bsk4r972yl',
  header: `Moravec's paradox is why the easy stuff is hardest for artificial intelligence.`,
  author: { name: 'Ashley Hamer' },
  link: { name: 'Curiosity', url: 'https://curiosity.com/topics/moravecs-paradox-is-why-the-easy-stuff-is-hardest-for-artificial-intelligence-curiosity/' },
  text: [
    paragraph(`The history of technology is full of predictions that now sound laughable. One of the most famous examples is credited to Bill Gates, who in 1981 is claimed to have said, "640 kilobytes ought to be enough for anybody." Predictions about artificial intelligence are no different; early AI researchers assumed that we'd have a robot that walked, talked, and thought like a human within decades. Of course, despite some awe-inspiring achievements in machine learning, AI still isn't there yet. That's because, according to a principle known as Moravec's paradox, we can teach machines to solve the hard problems, but it's the easy ones that are difficult.`),
    header(`Hey, Siri, Think Like a Toddler`),
    paragraph(`In 1957, economist and computer science pioneer Herbert Simon famously said, "It is not my aim to surprise or shock you — but the simplest way I can summarize is to say that there are now in the world machines that think, that learn and that create. Moreover, their ability to do these things is going to increase rapidly until — in a visible future — the range of problems they can handle will be coextensive with the range to which human mind has been applied."`),
    paragraph(`Simon died in 2001, and his "visible future" of a world where machines can think like humans is still a long way off. Sure, artificial intelligence has proven itself when tasked with specific problems, like categorizing distant galaxies or imitating celebrity voices or creating works of art, but simply thinking — a concept known as general artificial intelligence — seems to stymie the most advanced machine learning systems. Heck, even walking on two feet is a challenge for machines. They might be able to beat a grand champion at chess, but they can't beat a toddler at picking the right toy off the shelf.`),
    paragraph(`This isn't a new problem. In the 1980s, computer scientist Hans Moravec laid out this exact challenge — what has now been dubbed "Moravec's paradox" — and explained why it's just what we should expect from machines that are immune to the pressures of natural selection. "Encoded in the large, highly evolved sensory and motor portions of the human brain is a billion years of experience about the nature of the world and how to survive in it," he wrote in his 1988 book "Mind Children." "The deliberate process we call reasoning is, I believe, the thinnest veneer of human thought, effective only because it is supported by this much older and much more powerful, though usually unconscious, sensorimotor knowledge."`),
    paragraph(`That is to say, the things humans find easiest are the very things that took millennia of evolution to refine. The things humans find hardest are only hard because they're new — we've been thinking about chess strategy for a little over a thousand years, but we've been learning how to interact with our surroundings since our ancestors were single-celled organisms. The skills that are hardwired through evolution don't take conscious thought, and when you don't have to think about something, it's harder to figure out how to teach a machine to do it.`),
    header(`Know Machines by Knowing Ourselves`),
    paragraph(`So how do you teach a machine to truly think? Moravec thinks the answer lies in the very thing the machines lack: evolution. "I feel that the fastest progress can be made by imitating the evolution of animal minds, by striving to add capabilities to machines a few at a time, so that the resulting sequence of machine behaviors resembles the capabilities of animals with increasingly complex nervous systems," he wrote. Even at that time, however, things were improving. "Programs which tackle incremental problems similar to those that faced early animals — how to deal with, and even to anticipate, the sudden surprises, dangers, and opportunities encountered by an exploring organism — are being written and tested in robots that have to face the uncertainties of the real world."`),
    paragraph(`That progress continues today. Engineers are teaching artificial intelligence algorithms to be exploratory by having them play video games, for example. But it's a two-way street: Before we can teach machines to think like humans, we need to more fully understand how humans think, and understanding the limitations of machine learning can answer questions about how our minds truly work. Engineers designing neural networks can learn from neuroscientists and vice versa.`),
    paragraph(`It's possible that, as Steven Pinker predicts, the jobs in most danger of being overtaken by artificial intelligence are "the stock analysts and petrochemical engineers and parole board members," and it's the blue-collar workers like cooks and gardeners that are the ones with job security. It's also possible that the paradox means AI will never be truly independent and will always rely on the help of human users. But in either case, we should all take a moment to appreciate the supercomputers working inside of our skulls. They make the most difficult tasks in the world look easy.`),
  ],
  words: [
    { index: 0, id: '', meaning: [] },
    { index: 1, id: '', meaning: [] },
    { index: 2, id: '', meaning: [] },
    { index: 3, id: '', meaning: [] },
    { index: 4, id: '', meaning: [] },
    { index: 5, id: '', meaning: [] },
    { index: 6, id: '', meaning: [] },
    { index: 7, id: '', meaning: [] },
    { index: 8, id: '', meaning: [] },
    { index: 9, id: '', meaning: [] },
    { index: 10, id: '', meaning: [] },
    { index: 11, id: '', meaning: [] },
    { index: 12, id: '', meaning: [] },
    { index: 13, id: '', meaning: [] },
    { index: 14, id: '', meaning: [] },
    { index: 15, id: '', meaning: [] },
    { index: 16, id: '', meaning: [] },
    { index: 17, id: '', meaning: [] },
    { index: 18, id: '', meaning: [] },
    { index: 19, id: '', meaning: [] },
    { index: 20, id: '', meaning: [] },
    { index: 21, id: '', meaning: [] },
    { index: 22, id: '', meaning: [] },
    { index: 23, id: '', meaning: [] },
    { index: 24, id: '', meaning: [] },
    { index: 25, id: '', meaning: [] },
    { index: 26, id: '', meaning: [] },
    { index: 27, id: '', meaning: [] },
    { index: 28, id: '', meaning: [] },
    { index: 29, id: '', meaning: [] },
    { index: 30, id: '', meaning: [] },
    { index: 31, id: '', meaning: [] },
    { index: 32, id: '', meaning: [] },
    { index: 33, id: '', meaning: [] },
    { index: 34, id: '', meaning: [] },
    { index: 35, id: '', meaning: [] },
    { index: 36, id: '', meaning: [] },
    { index: 37, id: '', meaning: [] },
    { index: 38, id: '', meaning: [] },
    { index: 39, id: '', meaning: [] },
    { index: 40, id: '', meaning: [] },
    { index: 41, id: '', meaning: [] },
    { index: 42, id: '', meaning: [] },
    { index: 43, id: '', meaning: [] },
    { index: 44, id: '', meaning: [] },
    { index: 45, id: '', meaning: [] },
    { index: 46, id: '', meaning: [] },
    { index: 47, id: '', meaning: [] },
    { index: 48, id: '', meaning: [] },
    { index: 49, id: '', meaning: [] },
    { index: 50, id: '', meaning: [] },
    { index: 51, id: '', meaning: [] },
    { index: 52, id: '', meaning: [] },
    { index: 53, id: '', meaning: [] },
    { index: 54, id: '', meaning: [] },
    { index: 55, id: '', meaning: [] },
    { index: 56, id: '', meaning: [] },
    { index: 57, id: '', meaning: [] },
    { index: 58, id: '', meaning: [] },
    { index: 59, id: '', meaning: [] },
    { index: 60, id: '', meaning: [] },
    { index: 61, id: '', meaning: [] },
    { index: 62, id: '', meaning: [] },
    { index: 63, id: '', meaning: [] },
    { index: 64, id: '', meaning: [] },
    { index: 65, id: '', meaning: [] },
    { index: 66, id: '', meaning: [] },
    { index: 67, id: '', meaning: [] },
    { index: 68, id: '', meaning: [] },
    { index: 69, id: '', meaning: [] },
    { index: 70, id: '', meaning: [] },
    { index: 71, id: '', meaning: [] },
    { index: 72, id: '', meaning: [] },
    { index: 73, id: '', meaning: [] },
    { index: 74, id: '', meaning: [] },
    { index: 75, id: '', meaning: [] },
    { index: 76, id: '', meaning: [] },
    { index: 77, id: '', meaning: [] },
    { index: 78, id: '', meaning: [] },
    { index: 79, id: '', meaning: [] },
    { index: 80, id: '', meaning: [] },
    { index: 81, id: '', meaning: [] },
    { index: 82, id: '', meaning: [] },
    { index: 83, id: '', meaning: [] },
    { index: 84, id: '', meaning: [] },
    { index: 85, id: '', meaning: [] },
    { index: 86, id: '', meaning: [] },
    { index: 87, id: '', meaning: [] },
    { index: 88, id: '', meaning: [] },
    { index: 89, id: '', meaning: [] },
    { index: 90, id: '', meaning: [] },
    { index: 91, id: '', meaning: [] },
    { index: 92, id: '', meaning: [] },
    { index: 93, id: '', meaning: [] },
    { index: 94, id: '', meaning: [] },
    { index: 95, id: '', meaning: [] },
    { index: 96, id: '', meaning: [] },
    { index: 97, id: '', meaning: [] },
    { index: 98, id: '', meaning: [] },
    { index: 99, id: '', meaning: [] },
    { index: 100, id: '', meaning: [] },
    { index: 101, id: '', meaning: [] },
    { index: 102, id: '', meaning: [] },
    { index: 103, id: '', meaning: [] },
    { index: 104, id: '', meaning: [] },
  ]
};